[tool.black]
line-length = 120
target-version = ['py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
node_modules
| .DS_Store
| .idea
| __pycache__
| .pytest_cache
| backup
| backups
| files
| frontend
| log
| static
| staticfiles
| tmp
)
'''

[tool.isort]
profile = "black"
line_length = 120

[tool.poetry]
name = "tiloc"
version = "0.1.0"
description = ""
authors = ["Cédric RICARD <ricard33@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
arrow = "^1.2.3"
babel = "^2.10.3"
django = "^4.1.2"
django-constance = "^3.1.0"
django-cors-headers = "^4.2.0"
django-cron = "^0.6.0"
django-dbbackup = "^4.0.2"
django-filter = "^23.2"
django-import-export = "^3.2.0"
django-picklefield = "^3.1"
django-proxy = "^1.2.1"
django-rest-knox = "^4.2.0"
django-simple-history = "^3.1.1"
djangorestframework = "^3.14.0"
gunicorn = "^21.2.0"
ics = { git = "https://github.com/ricard33/ics-py", branch="more-permissive-parsing" }
invoke = "^2.1.3"
jinja2 = "^3.1.2"
JSON-log-formatter = "^0.5.1"
loggly-python-handler = "^1.0.1"
my-django-tweaks = "^0.0.6"
newrelic = "^9.0.0"
pdfkit = "^1.0.0"
Pillow = "^10.1.0"
requests = "^2.28.1"
smartconfigparser = "^1.0.0"
whitenoise = { version = "^6.2.0", extras = ["brotli"] }
psycopg2-binary = "^2.9.7"
faker = "^20.1.0"
django-email-verification = "^0.3.3"
stripe = "^7.5.0"
django-notifier-plus = {git = "https://github.com/ricard33/django-notifier-plus.git", develop = true}
django-timezone-field = "^6.1.0"

[tool.poetry.group.dev.dependencies]
coverage = "^7.3.2"
fabric = "^3.0"
factory_boy = "*"
flake8 = "^6.1.0"
isort = "^5.6.4"
patchwork = {git = "https://github.com/ricard33/patchwork.git", rev = "fabric3"}
pep8 = "^1.7.1"
pytest = "^7.4.3"
pytest-django = "^4.7.0"
black = "^23.11.0"
pytest-cov = "^4.0.0"
setuptools = "^69.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
