# Generated by Django 3.0.2 on 2020-01-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BookingChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.TextField(blank=True, help_text='Phone number and email as displayed in contracts, invoices, etc...', null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('legal', models.TextField(blank=True, help_text='Legal mention on bills', null=True)),
                ('payment', models.TextField(blank=True, help_text='Payment information', null=True)),
                ('billing', models.TextField(blank=True, help_text='Billing conditions', null=True)),
                ('no_vat', models.BooleanField()),
                ('vat_rate', models.DecimalField(blank=True, db_column='proprietaire_tva1', decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField()),
                ('invoice_label', models.CharField(max_length=30)),
                ('deposit_label', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='')),
                ('signature', models.ImageField(upload_to='')),
                ('display_week', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(max_length=256)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auto_add_booking', models.BooleanField(default=False)),
                ('auto_add_invoice', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('address', models.TextField()),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guaranty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('information', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=256)),
                ('customer_contact', models.TextField(blank=True, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('babies', models.PositiveSmallIntegerField(default=0)),
                ('catering', models.CharField(choices=[('none', 'None'), ('breakfast', 'Breakfast'), ('half', 'Half board'), ('full', 'Full board')], default='none', max_length=20)),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Overwrite daily price computation if set', max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price, either computed by daily price or applying flat rate', max_digits=10)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('guaranty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('contract', models.FileField(blank=True, null=True, upload_to='')),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('special_conditions', models.TextField(blank=True, null=True, verbose_name='Special conditions')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lodging')),
                ('options', models.ManyToManyField(through='core.BookedService', to='core.Service')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.BookingChannel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.BookingStatus')),
            ],
        ),
        migrations.AddField(
            model_name='bookedservice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Booking'),
        ),
        migrations.AddField(
            model_name='bookedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service'),
        ),
    ]
