# Generated by Django 4.2.3 on 2023-08-03 15:15

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BookedService",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="unit price VAT incl."
                    ),
                ),
                (
                    "is_flat_rate",
                    models.BooleanField(
                        default=False,
                        help_text="Use flat rate price instead of daily price computation",
                        verbose_name="flat rate?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking service",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("guest_name", models.CharField(max_length=256, verbose_name="guest name")),
                ("guest_contact", models.TextField(blank=True, null=True, verbose_name="guest contact")),
                ("guest_address", models.TextField(blank=True, null=True, verbose_name="guest address")),
                (
                    "source_uid",
                    models.CharField(
                        blank=True,
                        help_text="UID on source channel",
                        max_length=256,
                        null=True,
                        verbose_name="channel UID",
                    ),
                ),
                ("begin_date", models.DateField(verbose_name="begin date")),
                ("end_date", models.DateField(verbose_name="end date")),
                ("duration", models.PositiveSmallIntegerField(verbose_name="duration")),
                ("adults", models.PositiveSmallIntegerField(default=1, verbose_name="adults")),
                ("children", models.PositiveSmallIntegerField(default=0, verbose_name="children")),
                ("babies", models.PositiveSmallIntegerField(default=0, verbose_name="babies")),
                (
                    "catering",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("breakfast", "Breakfast"),
                            ("half", "Half board"),
                            ("full", "Full board"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="catering",
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="daily rate"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price, either computed by daily price or applying flat rate",
                        max_digits=20,
                        verbose_name="price",
                    ),
                ),
                (
                    "is_flat_rate",
                    models.BooleanField(
                        default=False,
                        help_text="Use flat rate price instead of daily price computation if true",
                        verbose_name="flat rate?",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="deposit"),
                ),
                (
                    "guaranty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="guaranty"
                    ),
                ),
                (
                    "commission_fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="commission fees"
                    ),
                ),
                (
                    "arrival_details",
                    models.CharField(
                        blank=True,
                        help_text="Arrival time, flight number, etc...",
                        max_length=100,
                        null=True,
                        verbose_name="arrival details",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notes")),
                (
                    "cancelled",
                    models.BooleanField(
                        default=False, help_text="True if this booking was cancelled", verbose_name="cancelled"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False, help_text="True if this booking was deleted", verbose_name="deleted"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Booking",
                "ordering": ("-begin_date",),
                "permissions": [("view_prices", "Can view prices informations")],
            },
        ),
        migrations.CreateModel(
            name="BookingChannel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "Booking channel",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookingStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("color", models.CharField(max_length=20, verbose_name="color")),
                ("rank", models.PositiveSmallIntegerField(verbose_name="rank")),
                (
                    "no_stats",
                    models.BooleanField(
                        default=False, help_text="Check to ignore from statistics bookings with this status"
                    ),
                ),
                (
                    "finalized",
                    models.BooleanField(
                        default=True, help_text="If true, the booking is finalized and considered as real"
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking status",
                "verbose_name_plural": "Booking statuses",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField(verbose_name="Contract")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contract template",
            },
        ),
        migrations.CreateModel(
            name="Holidays",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                ("begin_date", models.DateField(verbose_name="begin date")),
                ("end_date", models.DateField(verbose_name="end date")),
            ],
            options={
                "verbose_name_plural": "holidays",
            },
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                (
                    "daily_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="daily rate"
                    ),
                ),
                (
                    "weekend_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="weekend rate"
                    ),
                ),
                (
                    "weekly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="weekly rate"
                    ),
                ),
                ("minimum_stay", models.PositiveSmallIntegerField(verbose_name="Minimum stay")),
                (
                    "included_guests",
                    models.PositiveSmallIntegerField(verbose_name="Number of guests included in the price"),
                ),
                (
                    "supplement_per_additional_guest",
                    models.PositiveSmallIntegerField(verbose_name="Supplement per night and per additional guest"),
                ),
                ("info", models.TextField(blank=True, null=True, verbose_name="info")),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone", models.CharField(blank=True, max_length=30, null=True, verbose_name="phone")),
                (
                    "contact",
                    models.TextField(
                        blank=True,
                        help_text="Phone number and email as displayed in contracts, invoices, etc...",
                        null=True,
                        verbose_name="contact",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True, verbose_name="address")),
                (
                    "legal",
                    models.TextField(
                        blank=True, help_text="Legal mention on bills", null=True, verbose_name="legal mention"
                    ),
                ),
                (
                    "payment",
                    models.TextField(blank=True, help_text="Payment information", null=True, verbose_name="payment"),
                ),
                (
                    "billing",
                    models.TextField(blank=True, help_text="Billing conditions", null=True, verbose_name="billing"),
                ),
                ("no_vat", models.BooleanField(verbose_name="no vat")),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="vat rate"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "invoice_label",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("note", "Note"),
                            ("receipt", "Receipt"),
                            ("quittance", "Quittance"),
                        ],
                        default="receipt",
                        max_length=30,
                        verbose_name="invoice label",
                    ),
                ),
                (
                    "deposit_label",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("down_payment", "Down payment")],
                        default="deposit",
                        max_length=30,
                        verbose_name="deposit or down payment",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.user_directory_path, verbose_name="logo"
                    ),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.user_directory_path, verbose_name="signature"
                    ),
                ),
                ("display_week", models.BooleanField(default=False, verbose_name="display week number")),
            ],
            options={
                "verbose_name": "Property",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(blank=True, max_length=20, null=True, verbose_name="reference")),
                ("designation", models.CharField(max_length=256, verbose_name="designation")),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="unit price VAT incl."
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="VAT %"),
                ),
                (
                    "is_flat_rate",
                    models.BooleanField(
                        default=False,
                        help_text="Use flat rate price instead of daily price computation",
                        verbose_name="flat rate?",
                    ),
                ),
                (
                    "included_in_booking",
                    models.BooleanField(
                        default=False,
                        help_text="If true, the price of this option is included in booking price and not displayed separately",
                        verbose_name="included in booking",
                    ),
                ),
                (
                    "not_included_in_price",
                    models.BooleanField(
                        default=False,
                        help_text="Service not included in current booking price. Maybe provided by external partner...",
                        verbose_name="not included in price",
                    ),
                ),
                ("auto_add_booking", models.BooleanField(default=False, verbose_name="auto add booking")),
                ("auto_add_invoice", models.BooleanField(default=False, verbose_name="auto add invoice")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "ordering": ("reference",),
            },
        ),
        migrations.CreateModel(
            name="SeasonalVariation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                ("begin_date", models.DateField(verbose_name="begin date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "daily_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="daily rate"
                    ),
                ),
                (
                    "weekend_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="weekend rate"
                    ),
                ),
                (
                    "weekly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="weekly rate"
                    ),
                ),
                ("minimum_stay", models.PositiveSmallIntegerField(verbose_name="Minimum stay")),
                ("pricing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.pricing")),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=255, verbose_name="description")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20, verbose_name="amount")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_card", "Bank card"),
                            ("check", "Check"),
                            ("transfer", "Transfer"),
                            ("paypal", "PayPal"),
                            ("vouchers", "Holiday vouchers"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Payment method",
                    ),
                ),
                ("date", models.DateField(verbose_name="Payment date")),
                (
                    "checked",
                    models.BooleanField(
                        default=False, help_text="Used for account reconciliation", verbose_name="Checked"
                    ),
                ),
                ("booking", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.booking")),
            ],
            options={
                "ordering": ["date"],
                "permissions": [("reconciliation", "Can do account reconciliation")],
            },
        ),
        migrations.CreateModel(
            name="Lodging",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("shown", models.BooleanField(default=True, verbose_name="shown")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="name")),
                ("rank", models.IntegerField(verbose_name="rank")),
                ("address", models.TextField(verbose_name="address")),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default price for one night",
                        max_digits=20,
                        verbose_name="daily rate",
                    ),
                ),
                (
                    "guaranty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="guaranty deposit"
                    ),
                ),
                ("capacity", models.IntegerField(blank=True, null=True, verbose_name="capacity")),
                ("information", models.TextField(blank=True, verbose_name="information")),
                (
                    "tourist_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="tourist tax"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Used by contracts generation", verbose_name="description"),
                ),
                (
                    "contract_template",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.contracttemplate"
                    ),
                ),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.property")),
            ],
            options={
                "verbose_name": "Lodging",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalService",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("reference", models.CharField(blank=True, max_length=20, null=True, verbose_name="reference")),
                ("designation", models.CharField(max_length=256, verbose_name="designation")),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="unit price VAT incl."
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="VAT %"),
                ),
                (
                    "is_flat_rate",
                    models.BooleanField(
                        default=False,
                        help_text="Use flat rate price instead of daily price computation",
                        verbose_name="flat rate?",
                    ),
                ),
                (
                    "included_in_booking",
                    models.BooleanField(
                        default=False,
                        help_text="If true, the price of this option is included in booking price and not displayed separately",
                        verbose_name="included in booking",
                    ),
                ),
                (
                    "not_included_in_price",
                    models.BooleanField(
                        default=False,
                        help_text="Service not included in current booking price. Maybe provided by external partner...",
                        verbose_name="not included in price",
                    ),
                ),
                ("auto_add_booking", models.BooleanField(default=False, verbose_name="auto add booking")),
                ("auto_add_invoice", models.BooleanField(default=False, verbose_name="auto add invoice")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.category",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Service",
                "verbose_name_plural": "historical Services",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProperty",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("name", models.CharField(db_index=True, max_length=200, verbose_name="name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone", models.CharField(blank=True, max_length=30, null=True, verbose_name="phone")),
                (
                    "contact",
                    models.TextField(
                        blank=True,
                        help_text="Phone number and email as displayed in contracts, invoices, etc...",
                        null=True,
                        verbose_name="contact",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True, verbose_name="address")),
                (
                    "legal",
                    models.TextField(
                        blank=True, help_text="Legal mention on bills", null=True, verbose_name="legal mention"
                    ),
                ),
                (
                    "payment",
                    models.TextField(blank=True, help_text="Payment information", null=True, verbose_name="payment"),
                ),
                (
                    "billing",
                    models.TextField(blank=True, help_text="Billing conditions", null=True, verbose_name="billing"),
                ),
                ("no_vat", models.BooleanField(verbose_name="no vat")),
                (
                    "vat_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="vat rate"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "invoice_label",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("note", "Note"),
                            ("receipt", "Receipt"),
                            ("quittance", "Quittance"),
                        ],
                        default="receipt",
                        max_length=30,
                        verbose_name="invoice label",
                    ),
                ),
                (
                    "deposit_label",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("down_payment", "Down payment")],
                        default="deposit",
                        max_length=30,
                        verbose_name="deposit or down payment",
                    ),
                ),
                ("logo", models.TextField(blank=True, max_length=100, null=True, verbose_name="logo")),
                ("signature", models.TextField(blank=True, max_length=100, null=True, verbose_name="signature")),
                ("display_week", models.BooleanField(default=False, verbose_name="display week number")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Property",
                "verbose_name_plural": "historical Propertys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLodging",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("shown", models.BooleanField(default=True, verbose_name="shown")),
                ("name", models.CharField(db_index=True, max_length=200, verbose_name="name")),
                ("rank", models.IntegerField(verbose_name="rank")),
                ("address", models.TextField(verbose_name="address")),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default price for one night",
                        max_digits=20,
                        verbose_name="daily rate",
                    ),
                ),
                (
                    "guaranty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="guaranty deposit"
                    ),
                ),
                ("capacity", models.IntegerField(blank=True, null=True, verbose_name="capacity")),
                ("information", models.TextField(blank=True, verbose_name="information")),
                (
                    "tourist_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="tourist tax"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Used by contracts generation", verbose_name="description"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "contract_template",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.contracttemplate",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Lodging",
                "verbose_name_plural": "historical Lodgings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContractTemplate",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField(verbose_name="Contract")),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Contract template",
                "verbose_name_plural": "historical Contract templates",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBooking",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("uid", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("guest_name", models.CharField(max_length=256, verbose_name="guest name")),
                ("guest_contact", models.TextField(blank=True, null=True, verbose_name="guest contact")),
                ("guest_address", models.TextField(blank=True, null=True, verbose_name="guest address")),
                (
                    "source_uid",
                    models.CharField(
                        blank=True,
                        help_text="UID on source channel",
                        max_length=256,
                        null=True,
                        verbose_name="channel UID",
                    ),
                ),
                ("begin_date", models.DateField(verbose_name="begin date")),
                ("end_date", models.DateField(verbose_name="end date")),
                ("duration", models.PositiveSmallIntegerField(verbose_name="duration")),
                ("adults", models.PositiveSmallIntegerField(default=1, verbose_name="adults")),
                ("children", models.PositiveSmallIntegerField(default=0, verbose_name="children")),
                ("babies", models.PositiveSmallIntegerField(default=0, verbose_name="babies")),
                (
                    "catering",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("breakfast", "Breakfast"),
                            ("half", "Half board"),
                            ("full", "Full board"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="catering",
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="daily rate"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price, either computed by daily price or applying flat rate",
                        max_digits=20,
                        verbose_name="price",
                    ),
                ),
                (
                    "is_flat_rate",
                    models.BooleanField(
                        default=False,
                        help_text="Use flat rate price instead of daily price computation if true",
                        verbose_name="flat rate?",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="deposit"),
                ),
                (
                    "guaranty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="guaranty"
                    ),
                ),
                (
                    "commission_fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="commission fees"
                    ),
                ),
                (
                    "arrival_details",
                    models.CharField(
                        blank=True,
                        help_text="Arrival time, flight number, etc...",
                        max_length=100,
                        null=True,
                        verbose_name="arrival details",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notes")),
                (
                    "cancelled",
                    models.BooleanField(
                        default=False, help_text="True if this booking was cancelled", verbose_name="cancelled"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False, help_text="True if this booking was deleted", verbose_name="deleted"
                    ),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lodging",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.lodging",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.bookingchannel",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.bookingstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Booking",
                "verbose_name_plural": "historical Bookings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(verbose_name="Contract")),
                ("pdf", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("pdf_created", models.DateTimeField(blank=True, null=True)),
                ("signed", models.DateTimeField(blank=True, null=True, verbose_name="signed")),
                ("booking", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="core.booking")),
            ],
            options={
                "verbose_name": "Contract",
            },
        ),
        migrations.CreateModel(
            name="BookingChannelSync",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_url", models.URLField(verbose_name="Source URL")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "last_import",
                    models.DateTimeField(
                        blank=True, help_text="Last time we imported remote calendar from channel.", null=True
                    ),
                ),
                (
                    "last_export",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the calendar has been successfully requested by remote channel.",
                        null=True,
                    ),
                ),
                ("last_import_error", models.TextField(blank=True, null=True)),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.bookingchannel")),
                ("lodging", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.lodging")),
            ],
        ),
        migrations.AddField(
            model_name="bookingchannel",
            name="default_booking_status",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.bookingstatus"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="lodging",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.lodging"),
        ),
        migrations.AddField(
            model_name="booking",
            name="options",
            field=models.ManyToManyField(through="core.BookedService", to="core.service"),
        ),
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.bookingchannel"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.bookingstatus"),
        ),
        migrations.AddField(
            model_name="bookedservice",
            name="booking",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.booking"),
        ),
        migrations.AddField(
            model_name="bookedservice",
            name="service",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.service"),
        ),
    ]
