# Generated by Django 4.2.3 on 2023-08-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0005_alter_user_unique_together_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('account', 'name')},
        ),
    ]
