# Generated by Django 4.2.3 on 2023-07-27 14:45

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models

import core.models


def add_first_account(apps, schema_editor):
    Account = apps.get_model("core", "Account")
    Account.objects.create(id=1, name="default")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_squashed_0018_rename_user_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name, should be unique", max_length=200, unique=True, verbose_name="name"
                    ),
                ),
            ],
            options={
                "permissions": (("administrator", "Can administer all account data"),),
            },
        ),
        migrations.RunPython(add_first_account, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.MyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="properties",
            field=models.ManyToManyField(
                blank=True,
                help_text="The properties this user has access.",
                related_name="users",
                related_query_name="user",
                to="core.property",
                verbose_name="properties",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AddField(
            model_name="bookingchannel",
            name="account",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingstatus",
            name="account",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="account",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contracttemplate",
            name="account",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontracttemplate",
            name="account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.account",
                verbose_name="account",
            ),
        ),
        migrations.AddField(
            model_name="historicalproperty",
            name="account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.account",
                verbose_name="account",
            ),
        ),
        migrations.AddField(
            model_name="historicalservice",
            name="account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.account",
                verbose_name="account",
            ),
        ),
        migrations.AddField(
            model_name="holidays",
            name="account",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="account",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="account",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="account",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="account",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("account", "username")},
        ),
    ]
