# Generated by Django 3.0.3 on 2020-02-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedservice',
            options={'verbose_name': 'Booking service'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking'},
        ),
        migrations.AlterModelOptions(
            name='bookingchannel',
            options={'verbose_name': 'Booking channel'},
        ),
        migrations.AlterModelOptions(
            name='bookingstatus',
            options={'verbose_name': 'Booking status', 'verbose_name_plural': 'Booking statuses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='lodging',
            options={'verbose_name': 'Lodging'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service'},
        ),
        migrations.AlterField(
            model_name='bookedservice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='adults'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='babies',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='babies'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='begin_date',
            field=models.DateField(verbose_name='begin date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='catering',
            field=models.CharField(choices=[('none', 'None'), ('breakfast', 'Breakfast'), ('half', 'Half board'), ('full', 'Full board')], default='none', max_length=20, verbose_name='catering'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='children'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='contract'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='contract date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_address',
            field=models.TextField(blank=True, null=True, verbose_name='customer address'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_contact',
            field=models.TextField(blank=True, null=True, verbose_name='customer contact'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=256, verbose_name='customer name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='daily price'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='deposit'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overwrite daily price computation if set', max_digits=10, null=True, verbose_name='flat rate'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guaranty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='guaranty'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Total price, either computed by daily price or applying flat rate', max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='bookingchannel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='bookingstatus',
            name='color',
            field=models.CharField(max_length=10, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='bookingstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='capacity',
            field=models.IntegerField(verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cleaning fee'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='default price'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='guaranty',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='guaranty deposit'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='information',
            field=models.TextField(verbose_name='information'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='rank',
            field=models.IntegerField(verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='billing',
            field=models.TextField(blank=True, help_text='Billing conditions', null=True, verbose_name='billing'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact',
            field=models.TextField(blank=True, help_text='Phone number and email as displayed in contracts, invoices, etc...', null=True, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='deposit_label',
            field=models.CharField(max_length=30, verbose_name='deposit label'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='display_week',
            field=models.NullBooleanField(verbose_name='display week'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='invoice_label',
            field=models.CharField(max_length=30, verbose_name='invoice label'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='legal',
            field=models.TextField(blank=True, help_text='Legal mention on bills', null=True, verbose_name='legal mention'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='no_vat',
            field=models.BooleanField(verbose_name='no vat'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='note',
            field=models.TextField(verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='payment',
            field=models.TextField(blank=True, help_text='Payment information', null=True, verbose_name='payment'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='signature',
            field=models.ImageField(upload_to='', verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='vat_rate',
            field=models.DecimalField(blank=True, db_column='proprietaire_tva1', decimal_places=2, max_digits=10, null=True, verbose_name='vat rate'),
        ),
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='auto_add_booking',
            field=models.BooleanField(default=False, verbose_name='auto add booking'),
        ),
        migrations.AlterField(
            model_name='service',
            name='auto_add_invoice',
            field=models.BooleanField(default=False, verbose_name='auto add invoice'),
        ),
        migrations.AlterField(
            model_name='service',
            name='designation',
            field=models.CharField(max_length=256, verbose_name='designation'),
        ),
        migrations.AlterField(
            model_name='service',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='service',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='unit price VAT excl.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VAT %'),
        ),
    ]
