# Generated by Django 3.0.3 on 2020-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='deposit_label',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('down_payment', 'Down payment')], default='deposit', max_length=30, verbose_name='deposit or down payment'),
        ),
    ]
