# Generated by Django 4.2.4 on 2023-08-29 17:49

from django.db import migrations, models
from django.db.models import F


def copy_property_name(apps, schema_editor):
    Property = apps.get_model("core", "Property")
    Property.objects.update(contractual_name=F("name"))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_property_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproperty',
            name='contractual_name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='contractual_name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalproperty',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.RunPython(copy_property_name, migrations.RunPython.noop)
    ]
