# Generated by Django 4.2.3 on 2023-07-29 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_account_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalservice",
            name="category",
        ),
        migrations.RemoveField(
            model_name="service",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
