# Generated by Django 3.2.6 on 2021-09-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_options price modifiable and quantity removed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="info",
        ),
        migrations.RemoveField(
            model_name="historicalbooking",
            name="info",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="special_conditions",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="historicalbooking",
            old_name="special_conditions",
            new_name="notes",
        ),
        migrations.AlterField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
    ]
