# Generated by Django 3.2.7 on 2021-12-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_migrate_special_conditions_to_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-begin_date',), 'verbose_name': 'Booking'},
        ),
    ]
