# Generated by Django 3.0.3 on 2020-02-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_Alter field deposit_label on owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='display_week',
            field=models.BooleanField(default=False, verbose_name='display week number'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='vat rate'),
        ),
    ]
