# Generated by Django 3.0.3 on 2020-02-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200221_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstatus',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='rank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='invoice_label',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('note', 'Note'), ('receipt', 'Receipt'), ('quittance', 'Quittance')], default='receipt', max_length=30, verbose_name='invoice label'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='logo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='signature',
            field=models.ImageField(blank=True, upload_to='', verbose_name='signature'),
        ),
    ]
