# Generated by Django 4.2.4 on 2023-10-05 20:13

import arrow
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=arrow.Arrow(2020, 1, 1, 0, 0).datetime),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='validity',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, help_text='Define if email user has been verified or not', verbose_name='verified'),
        ),
    ]
