# Generated by Django 3.0.3 on 2020-02-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200221_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingstatus',
            options={'ordering': ['rank'], 'verbose_name': 'Booking status', 'verbose_name_plural': 'Booking statuses'},
        ),
        migrations.RemoveField(
            model_name='lodging',
            name='property',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
