# Generated by Django 4.2.4 on 2023-10-11 21:44
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


def fill_default_fields(apps, schema_editor):
    Lodging = apps.get_model("core", "Lodging")
    for lodging in Lodging.objects.all():
        lodging.account = lodging.property.account
        lodging.owner = lodging.account.user_set.first()
        lodging.save(update_fields=("account", "owner",))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_account_created_account_validity_user_verified"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="property",
            unique_together=None,
        ),
        migrations.AddField(
            model_name="account",
            name="deposit_label",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("down_payment", "Down payment")],
                default="deposit",
                max_length=30,
                verbose_name="deposit or down payment",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="invoice_label",
            field=models.CharField(
                choices=[("invoice", "Invoice"), ("note", "Note"), ("receipt", "Receipt"), ("quittance", "Quittance")],
                default="receipt",
                max_length=30,
                verbose_name="invoice label",
            ),
        ),
        migrations.AddField(
            model_name="historicallodging",
            name="account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.account",
                verbose_name="account",
            ),
        ),
        migrations.AddField(
            model_name="historicallodging",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="lodging",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account", null=True
            ),
        ),
        migrations.AddField(
            model_name="lodging",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="user",
            name="billing",
            field=models.TextField(blank=True, help_text="Billing conditions", null=True, verbose_name="billing"),
        ),
        migrations.AddField(
            model_name="user",
            name="legal",
            field=models.TextField(
                blank=True, help_text="Legal mention on bills", null=True, verbose_name="legal mention"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lodgings",
            field=models.ManyToManyField(
                blank=True,
                help_text="The lodgings this user has access.",
                related_name="users",
                related_query_name="user",
                to="core.lodging",
                verbose_name="lodgings",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.user_directory_path, verbose_name="logo"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="no_vat",
            field=models.BooleanField(default=True, verbose_name="no vat"),
        ),
        migrations.AddField(
            model_name="user",
            name="payment",
            field=models.TextField(blank=True, help_text="Payment information", null=True, verbose_name="payment"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="phone"),
        ),
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.user_directory_path, verbose_name="signature"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="vat_rate",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="vat rate"),
        ),
        migrations.AlterField(
            model_name="historicallodging",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="lodging",
            name="name",
            field=models.CharField(max_length=200, verbose_name="name"),
        ),
        migrations.AlterUniqueTogether(
            name="lodging",
            unique_together={("account", "name")},
        ),

        migrations.RunPython(fill_default_fields, migrations.RunPython.noop),

        migrations.AlterField(
            model_name="lodging",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
            ),
        ),
        migrations.AlterField(
            model_name="lodging",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="owner"
            ),
        ),
        migrations.RemoveField(
            model_name="property",
            name="account",
        ),
        migrations.RemoveField(
            model_name="user",
            name="properties",
        ),
        migrations.RemoveField(
            model_name="historicallodging",
            name="property",
        ),
        migrations.RemoveField(
            model_name="lodging",
            name="property",
        ),
        migrations.DeleteModel(
            name="HistoricalProperty",
        ),
        migrations.DeleteModel(
            name="Property",
        ),
    ]
