# Generated by Django 3.0.3 on 2020-02-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200222_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='cleaning_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cleaning fee'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='default_price',
            field=models.DecimalField(decimal_places=2, help_text='Default price for one night', max_digits=10, verbose_name='daily default price'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='guaranty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='guaranty deposit'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='information',
            field=models.TextField(blank=True, verbose_name='information'),
        ),
    ]
