# Generated by Django 4.2.4 on 2023-10-19 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_status(apps, schema_editor):
    default_account_id = 1
    BookingStatus = apps.get_model("core", "BookingStatus")
    Booking = apps.get_model("core", "Booking")
    for status in BookingStatus.objects.exclude(account=default_account_id):
        # print(status)
        try:
            default_status = BookingStatus.objects.filter(account=default_account_id).get(name=status.name)
        except BookingStatus.DoesNotExist:
            default_status = BookingStatus.objects.filter(account=default_account_id).first()
        Booking.objects.filter(status=status).update(status=default_status)
    BookingStatus.objects.exclude(account=default_account_id).delete()
    # BookingStatus.objects.update(id0=Lower("name"))


def migrate_channel_sync(apps, schema_editor):
    default_account_id = 1
    BookingChannel = apps.get_model("core", "BookingChannel")
    for channel in BookingChannel.objects.filter(account__id=default_account_id):
        channel.account = None
        channel.save()

    for channel in BookingChannel.objects.exclude(account__id=default_account_id):
        try:
            global_channel = BookingChannel.objects.get(account__isnull=True, name=channel.name)
            channel.bookingchannelsync_set.update(channel=global_channel)
        except BookingChannel.DoesNotExist:
            pass

    BookingChannel.objects.exclude(account__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_property"),
    ]

    operations = [
        # BookingChannelSync
        migrations.AlterField(
            model_name="bookingchannel",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.account",
                verbose_name="account",
            ),
        ),
        migrations.RemoveField(
            model_name='bookingchannel',
            name='default_booking_status',
        ),
        migrations.AlterModelOptions(
            name='bookingchannel',
            options={'ordering': ['name'], 'verbose_name': 'Booking channel', 'verbose_name_plural': 'Booking channels'},
        ),
        migrations.RunPython(migrate_channel_sync, migrations.RunPython.noop),
        # BookingStatus
        migrations.RunPython(migrate_status, migrations.RunPython.noop),
        migrations.RemoveField("bookingstatus", "account"),
        # Old changes on Lodging
        migrations.AlterField(
            model_name="historicallodging",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="owned_lodging",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="lodging",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_lodgings",
                related_query_name="owned_lodging",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
    ]
