# Generated by Django 3.0.3 on 2020-02-22 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200222_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.BookingChannel'),
        ),
    ]
