# Generated by Django 4.1.2 on 2022-10-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_historicalbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingstatus',
            name='finalized',
            field=models.BooleanField(default=True, help_text='If true, the booking is finalized and considered as real'),
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='no_stats',
            field=models.BooleanField(default=False, help_text='Check to ignore from statistics bookings with this status'),
        ),
    ]
