# Generated by Django 4.2.4 on 2023-10-27 12:52

from django.db import migrations, models
from django.db.models import F, OuterRef


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_bookingstatus"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="status"),
        migrations.RenameField(model_name="booking", old_name="status_", new_name="status"),
        migrations.AlterField(
            model_name="historicalbooking",
            name="status",
            field=models.TextField(
                choices=[
                    ("not available", "Not available"),
                    ("option", "Option"),
                    ("contract sent", "Contract sent"),
                    ("deposit paid", "Deposit paid"),
                    ("payment on arrival", "Payment on arrival"),
                    ("paid", "Paid"),
                    ("external", "External"),
                ],
                default="not available",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.DeleteModel(
            name="BookingStatus",
        ),
    ]
