# Generated by Django 4.2.4 on 2023-10-27 12:52

from django.db import migrations, models
from django.db.models import F, OuterRef


def migrate_all_statuses_to_default_account_ones(apps, schema_editor):
    default_account_id = 1
    BookingStatus = apps.get_model("core", "BookingStatus")
    Booking = apps.get_model("core", "Booking")
    for status in BookingStatus.objects.exclude(account=default_account_id):
        # print(status)
        try:
            default_status = BookingStatus.objects.filter(account=default_account_id).get(name=status.name)
        except BookingStatus.DoesNotExist:
            default_status = BookingStatus.objects.filter(account=default_account_id).first()
        Booking.objects.filter(status=status).update(status=default_status)
    BookingStatus.objects.exclude(account=default_account_id).delete()
    # BookingStatus.objects.update(id0=Lower("name"))


def rename_status(apps, schema_editor):
    BookingStatus = apps.get_model("core", "BookingStatus")
    BookingStatus.objects.filter(name="Indisponible").update(name="not available")
    BookingStatus.objects.filter(name="Option").update(name="option")
    BookingStatus.objects.filter(name="Contrat envoyé").update(name="contract sent")
    BookingStatus.objects.filter(name="Arrhes payées").update(name="deposit paid")
    BookingStatus.objects.filter(name="Paiement à l'arrivée").update(name="payment on arrival")
    BookingStatus.objects.filter(name="Payé").update(name="paid")
    if not BookingStatus.objects.filter(name="external").exists():
        BookingStatus.objects.create(name="external", color="#DDDDDD", finalized=True, no_stats=False, rank=10, account_id=1)

    external = BookingStatus.objects.get(name="external")

    for name in ["Abritel", "Airbnb", "Booking.com", "Tripadvisor"]:
        try:
            status = BookingStatus.objects.get(name=name)
            status.booking_set.all().update(status=external)
            status.delete()
        except BookingStatus.DoesNotExist:
            pass

    Booking = apps.get_model("core", "Booking")
    Booking.objects.all().annotate(status_name=F("status__name"))
    Booking.objects.all().update(
        status_=Booking.objects.filter(id=OuterRef("id"))
        .annotate(status_name=F("status__name"))
        .values("status_name")[:1]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_bookingchannel_and_bookingchannelsync"),
    ]

    operations = [
        # BookingStatus
        migrations.AddField(
            model_name="booking",
            name="status_",
            field=models.TextField(
                choices=[
                    ("not available", "Not available"),
                    ("option", "Option"),
                    ("contract sent", "Contract sent"),
                    ("deposit paid", "Deposit paid"),
                    ("payment on arrival", "Payment on arrival"),
                    ("paid", "Paid"),
                    ("external", "External"),
                ],
                default="not available",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.RunPython(migrate_all_statuses_to_default_account_ones, migrations.RunPython.noop),
        migrations.RunPython(rename_status, migrations.RunPython.noop),
    ]
