# Generated by Django 4.2.4 on 2023-10-27 12:52

from django.db import migrations, models
from django.db.models import F, OuterRef


def rename_status(apps, schema_editor):
    BookingStatus = apps.get_model("core", "BookingStatus")
    BookingStatus.objects.filter(name="Indisponible").update(name="not available")
    BookingStatus.objects.filter(name="Option").update(name="option")
    BookingStatus.objects.filter(name="Contrat envoyé").update(name="contract sent")
    BookingStatus.objects.filter(name="Arrhes payées").update(name="deposit paid")
    BookingStatus.objects.filter(name="Paiement à l'arrivée").update(name="payment on arrival")
    BookingStatus.objects.filter(name="Payé").update(name="paid")
    if not BookingStatus.objects.filter(name="external").exists():
        BookingStatus.objects.create(name="external", color="#DDDDDD", finalized=True, no_stats=False, rank=10)

    external = BookingStatus.objects.get(name="external")

    for name in ["Abritel", "Airbnb", "Booking.com", "Tripadvisor"]:
        try:
            status = BookingStatus.objects.get(name=name)
            status.booking_set.all().update(status=external)
            status.delete()
        except BookingStatus.DoesNotExist:
            pass

    Booking = apps.get_model("core", "Booking")
    Booking.objects.all().annotate(status_name=F("status__name"))
    Booking.objects.all().update(
        status_=Booking.objects.filter(id=OuterRef("id"))
        .annotate(status_name=F("status__name"))
        .values("status_name")[:1]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_bookingchannelsync_channel0_bookingstatus_id0_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status_",
            field=models.TextField(
                choices=[
                    ("not available", "Not available"),
                    ("option", "Option"),
                    ("contract sent", "Contract sent"),
                    ("deposit paid", "Deposit paid"),
                    ("payment on arrival", "Payment on arrival"),
                    ("paid", "Paid"),
                    ("external", "External"),
                ],
                default="not available",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.RunPython(rename_status, migrations.RunPython.noop),
        migrations.RemoveField(model_name="booking", name="status"),
        migrations.RenameField(model_name="booking", old_name="status_", new_name="status"),
        migrations.AlterField(
            model_name="historicalbooking",
            name="status",
            field=models.TextField(
                choices=[
                    ("not available", "Not available"),
                    ("option", "Option"),
                    ("contract sent", "Contract sent"),
                    ("deposit paid", "Deposit paid"),
                    ("payment on arrival", "Payment on arrival"),
                    ("paid", "Paid"),
                    ("external", "External"),
                ],
                default="not available",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.DeleteModel(
            name="BookingStatus",
        ),
    ]
