# Generated by Django 3.0.5 on 2020-04-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200222_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Owner'),
            preserve_default=False,
        ),
    ]
