# Generated by Django 4.1.2 on 2022-11-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_bookingstatus_finalized_bookingstatus_no_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancelled",
            field=models.BooleanField(
                default=False, help_text="True if this booking was cancelled", verbose_name="cancelled"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="deleted",
            field=models.BooleanField(
                default=False, help_text="True if this booking was deleted", verbose_name="deleted"
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="cancelled",
            field=models.BooleanField(
                default=False, help_text="True if this booking was cancelled", verbose_name="cancelled"
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="deleted",
            field=models.BooleanField(
                default=False, help_text="True if this booking was deleted", verbose_name="deleted"
            ),
        ),
    ]
