# Generated by Django 4.2.4 on 2023-11-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_bookingstatus_remove_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="lodging",
            name="is_flat_rate_tourist_tax",
            field=models.BooleanField(default=True, verbose_name="flat rate tourist tax"),
        ),
        migrations.AddField(
            model_name="lodging",
            name="tourist_tax_included_in_payment",
            field=models.BooleanField(default=True, verbose_name="tourist tax included in payment"),
        ),
        migrations.AddField(
            model_name="lodging",
            name="tourist_tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="tourist tax rate"
            ),
        ),
        migrations.RenameField(
            model_name="lodging",
            old_name="tourist_tax",
            new_name="max_daily_tourist_tax",
        ),
        migrations.AddField(
            model_name="historicallodging",
            name="is_flat_rate_tourist_tax",
            field=models.BooleanField(default=True, verbose_name="flat rate tourist tax"),
        ),
        migrations.AddField(
            model_name="historicallodging",
            name="tourist_tax_included_in_payment",
            field=models.BooleanField(default=True, verbose_name="tourist tax included in payment"),
        ),
        migrations.AddField(
            model_name="historicallodging",
            name="tourist_tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="tourist tax rate"
            ),
        ),
        migrations.RenameField(
            model_name="historicallodging",
            old_name="tourist_tax",
            new_name="max_daily_tourist_tax",
        ),
        migrations.AlterField(
            model_name="lodging",
            name="max_daily_tourist_tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="max daily tourist tax"
            ),
        ),
        migrations.AlterField(
            model_name="historicallodging",
            name="max_daily_tourist_tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="max daily tourist tax"
            ),
        ),
    ]
