# Generated by Django 3.0.5 on 2020-04-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lodging_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='flat_rate',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_flat_rate',
            field=models.BooleanField(default=False, help_text='Use flat rate price insteed of daily price computation if true', verbose_name='flat rate'),
        ),
    ]
