# Generated by Django 4.1.2 on 2022-11-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_cancelled_booking_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lodging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lodging'),
        ),
    ]
