# Generated by Django 4.2.4 on 2023-11-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tourist_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_tourist_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='overwrite automated tourist tax', max_digits=20, null=True, verbose_name='personalized tourist tax'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='custom_tourist_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='overwrite automated tourist tax', max_digits=20, null=True, verbose_name='personalized tourist tax'),
        ),
        migrations.AlterField(
            model_name='historicallodging',
            name='tourist_tax_included_in_payment',
            field=models.BooleanField(default=True, help_text='An hidden feature for internal use only', verbose_name='tourist tax included in payment'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='tourist_tax_included_in_payment',
            field=models.BooleanField(default=True, help_text='An hidden feature for internal use only', verbose_name='tourist tax included in payment'),
        ),
    ]
