# Generated by Django 4.1.2 on 2022-11-07 12:57
import re

from django.db import migrations, models


def extract_fligh_data(apps, schema_editor):
    Booking = apps.get_model("core", "Booking")
    fligh_re = re.compile(r"^.*\d\dh\d\d.*$", re.MULTILINE | re.IGNORECASE)
    menage_re = re.compile("m[eé]nage", re.IGNORECASE)

    for booking in Booking.objects.filter(notes__isnull=False):
        arrival_details = []
        for line in fligh_re.findall(booking.notes):
            if not menage_re.search(line):
                arrival_details.append(line)
        if arrival_details:
            booking.arrival_details = ", ".join(arrival_details)
            booking.save(update_fields=["arrival_details"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_booking_lodging"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="arrival_details",
            field=models.CharField(
                blank=True,
                help_text="Arrival time, flight number, etc...",
                max_length=100,
                null=True,
                verbose_name="arrival details",
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="arrival_details",
            field=models.CharField(
                blank=True,
                help_text="Arrival time, flight number, etc...",
                max_length=100,
                null=True,
                verbose_name="arrival details",
            ),
        ),
        migrations.RunPython(extract_fligh_data, reverse_code=migrations.RunPython.noop),
    ]
