# Generated by Django 4.2.4 on 2023-11-06 00:58

from django.db import migrations


def remove_tourist_tax(apps, schema_editor):
    Booking = apps.get_model("core", "Booking")
    Booking.objects.filter(status = "external").update(custom_tourist_tax=0)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_booking_custom_tourist_tax'),
    ]

    operations = [
        migrations.RunPython(remove_tourist_tax, migrations.RunPython.noop)
    ]
