# Generated by Django 3.0.5 on 2020-04-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200429_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='daily_price',
        ),
        migrations.RemoveField(
            model_name='lodging',
            name='default_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='daily rate'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default price for one night', max_digits=10, verbose_name='daily rate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_flat_rate',
            field=models.BooleanField(default=False, help_text='Use flat rate price insteed of daily price computation if true', verbose_name='flat rate?'),
        ),
    ]
