# Generated by Django 4.2.4 on 2023-11-06 01:43

from django.db import migrations, models


def set_default_services(apps, schema_editor):
    Account = apps.get_model("core", "Account")
    Service = apps.get_model("core", "Service")
    Lodging = apps.get_model("core", "Lodging")
    for account in Account.objects.all():
        services = Service.objects.filter(account=account, auto_add_booking=True)
        if services.exists():
            for lodging in Lodging.objects.filter(account=account):
                lodging.default_services.set(services)
                # lodging.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_tourist_tax_from_external_bookings"),
    ]

    operations = [
        migrations.AddField(
            model_name="lodging",
            name="default_services",
            field=models.ManyToManyField(
                blank=True, help_text="Services added by default on new bookings", to="core.service"
            ),
        ),
        migrations.RunPython(set_default_services, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="service",
            name="reference",
            field=models.CharField(max_length=20, verbose_name="reference"),
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("account", "reference")},
        ),
        migrations.RemoveField(
            model_name='service',
            name='auto_add_booking',
        ),
        migrations.RemoveField(
            model_name='service',
            name='auto_add_invoice',
        ),
        migrations.RemoveField(
            model_name='service',
            name='included_in_booking',
        ),
        migrations.DeleteModel(
            name="HistoricalService",
        ),
    ]
