# Generated by Django 4.1.7 on 2023-03-26 14:04

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_booking_arrival_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalowner',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='historicalowner',
            name='signature',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path, verbose_name='signature'),
        ),
    ]
