# Generated by Django 4.2.4 on 2023-11-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lodging_default_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallodging',
            name='balance_due_date',
            field=models.IntegerField(default=0, help_text='When the balance should be paid (in days before arrival)', verbose_name='due date for balance (in days)'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='balance_due_date',
            field=models.IntegerField(default=0, help_text='When the balance should be paid (in days before arrival)', verbose_name='due date for balance (in days)'),
        ),
    ]
