# Generated by Django 3.0.7 on 2020-06-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200509_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lodging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Lodging'),
        ),
    ]
