# Generated by Django 4.1.7 on 2023-03-26 16:46

from django.db import migrations, models
from django.db.models import F


def fix_color_values(apps, schema_editor):
    BookingStatus = apps.get_model("core", "BookingStatus")
    for status in BookingStatus.objects.exclude(color__startswith="#"):
        status.color = "#" + status.color
        status.save(update_fields=["color"])


def unfix_color_values(apps, schema_editor):
    BookingStatus = apps.get_model("core", "BookingStatus")
    for status in BookingStatus.objects.filter(color__startswith="#"):
        status.color = status.color[1:]
        status.save(update_fields=["color"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_historicalowner_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingstatus",
            name="color",
            field=models.CharField(max_length=20, verbose_name="color"),
        ),
        migrations.RunPython(fix_color_values, reverse_code=unfix_color_values),
    ]
