# Generated by Django 4.1.7 on 2023-04-02 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_bookingstatus_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lodging',
            options={'ordering': ['rank'], 'verbose_name': 'Lodging'},
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category'),
        ),
    ]
