# Generated by Django 4.2.4 on 2023-11-26 09:58

import django.db.models.deletion
from django.db import migrations, models


def add_default_plans(apps, schema_editor):
    Plan = apps.get_model("core", "Plan")
    Plan.objects.create(ref="FREE", name="Basic", max_lodgings=1, max_users=1, price=0, interval='monthly')
    Plan.objects.create(ref="OWNER-MONTHLY", name="Essentiel", max_lodgings=3, max_users=1, price=10,
                        interval='monthly', lookup_key='tiloc-owner-monthly')
    Plan.objects.create(ref="PRO10-MONTHLY", name="Conciergerie", max_lodgings=10, max_users=10, price=25,
                        interval='monthly', lookup_key='tiloc-pro10-monthly')
    Plan.objects.create(ref="OWNER-YEARLY", name="Essentiel", max_lodgings=3, max_users=1, price=100,
                        interval='yearly', lookup_key='tiloc-owner-yearly')
    Plan.objects.create(ref="PRO10-YEARLY", name="Conciergerie", max_lodgings=10, max_users=10, price=250,
                        interval='yearly', lookup_key='tiloc-pro10-yearly')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lodging_balance_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('ref', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('max_lodgings', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_users', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('lookup_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.RunPython(
            code=add_default_plans,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='account',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='account',
            name='validity',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('past_due', 'past_due'), ('unpaid', 'unpaid'), ('canceled', 'canceled'), ('incomplete', 'incomplete'), ('incomplete_expired', 'incomplete_expired'), ('trialing', 'trialing'), ('paused', 'paused')], max_length=50)),
                ('latest_invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account', to_field='stripe_customer_id')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.plan', to_field='lookup_key')),
                ('default_payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
    ]
