# Generated by Django 3.0.7 on 2020-07-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200630_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('begin_date', models.DateField(verbose_name='begin date')),
                ('end_date', models.DateField(verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='daily rate')),
                ('weekend_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='weekend rate')),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='weekly rate')),
                ('minimum_stay', models.PositiveSmallIntegerField(verbose_name='Minimum stay')),
                ('included_guests', models.PositiveSmallIntegerField(verbose_name='Number of guests included in the price')),
                ('supplement_per_additional_guest', models.PositiveSmallIntegerField(verbose_name='Supplement per night and per aditional guest')),
                ('info', models.TextField(blank=True, null=True, verbose_name='info')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('begin_date', models.DateField(verbose_name='begin date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='daily rate')),
                ('weekend_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='weekend rate')),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='weekly rate')),
                ('minimum_stay', models.PositiveSmallIntegerField(verbose_name='Minimum stay')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pricing')),
            ],
        ),
        migrations.CreateModel(
            name='BookingChannelSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(verbose_name='Source URL')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BookingChannel')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lodging')),
            ],
        ),
    ]
