# Generated by Django 4.2.4 on 2023-11-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lodging_balance_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('ref', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('max_lodgings', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_users', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price_per_month', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.plan'),
        ),
    ]
