# Generated by Django 4.2.7 on 2023-12-06 01:17

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_stripe_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tz',
            field=timezone_field.fields.TimeZoneField(default='America/Martinique'),
        ),
    ]
