# Generated by Django 3.0.7 on 2020-07-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bookingchannelsync_holidays_pricing_seasonalvariation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidays',
            options={'verbose_name_plural': 'holidays'},
        ),
    ]
