# Generated by Django 4.2.3 on 2023-07-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_lodging_options_alter_service_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date'], 'permissions': [('reconciliation', 'Can do account reconciliation')]},
        ),
        migrations.AddField(
            model_name='payment',
            name='checked',
            field=models.BooleanField(default=False, help_text='Used for account reconciliation', verbose_name='Checked'),
        ),
    ]
