# Generated by Django 4.2.4 on 2023-11-16 17:21

from django.db import migrations


def add_default_plans(apps, schema_editor):
    Plan = apps.get_model("core", "Plan")
    Plan.objects.create(ref="FREE", name="Basic", max_lodgings=1, max_users=1, price_per_month=0)
    Plan.objects.create(ref="OWNER", name="Essentiel", max_lodgings=3, max_users=1, price_per_month=10)
    Plan.objects.create(ref="PRO10", name="Conciergerie", max_lodgings=10, max_users=10, price_per_month=25)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_plan_account_subscription"),
    ]

    operations = [migrations.RunPython(add_default_plans, migrations.RunPython.noop)]
