# Generated by Django 4.2.8 on 2023-12-08 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_tz'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRemovedByExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('see_count', models.IntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.booking')),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.bookingchannelsync')),
            ],
            options={
                'unique_together': {('sync', 'booking')},
            },
        ),
    ]
