# Generated by Django 4.2.3 on 2023-07-25 11:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_alter_payment_options_payment_checked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalOwner',
            new_name='HistoricalProperty',
        ),
        migrations.RenameModel(
            old_name='Owner',
            new_name='Property',
        ),
        migrations.AlterModelOptions(
            name='historicalproperty',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Property', 'verbose_name_plural': 'historical Propertys'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property'},
        ),
        migrations.RenameField(
            model_name='historicallodging',
            old_name='owner',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='lodging',
            old_name='owner',
            new_name='property',
        ),
    ]
