# Generated by Django 3.0.8 on 2020-07-03 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200702_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source_uid',
            field=models.CharField(blank=True, help_text='UID on source channel', max_length=256, null=True, verbose_name='channel UID'),
        ),
        migrations.AddField(
            model_name='bookingchannel',
            name='default_booking_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.BookingStatus'),
        ),
    ]
