# Generated by Django 3.0.8 on 2020-07-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200703_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingchannelsync',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
