# Generated by Django 4.2.4 on 2023-11-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_account_stripe_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='subscription',
            new_name='current_plan',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='price_per_month',
            new_name='price',
        ),
        migrations.AddField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='lookup_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('latest_invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account', to_field='stripe_customer_id')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.plan', to_field='lookup_key')),
            ],
        ),
    ]
