# Generated by Django 4.2.3 on 2023-07-27 13:51

from django.db import migrations


def change_user_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ct = ContentType.objects.filter(app_label="auth", model="user").first()
    if ct:
        ct.app_label = "core"
        ct.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_rename_owner_property_and_more"),
    ]

    operations = [
        migrations.RunPython(change_user_type, elidable=True),
    ]
