# Generated by Django 4.2.3 on 2023-07-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
