# Generated by Django 4.2.8 on 2023-12-22 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('add_booking', 'Add booking'), ('modify_booking', 'Modify booking'), ('delete_booking', 'Delete booking'), ('cancel_booking', 'Cancel booking'), ('uncancel_booking', 'Uncancel booking'), ('add_comment', 'Add comment'), ('modify_comment', 'Modify comment'), ('delete_comment', 'Delete comment')], max_length=50, verbose_name='Activity type')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.booking')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ('-date',),
            },
        ),
    ]
