# Generated by Django 4.2.4 on 2023-11-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_subscription_account_current_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='validity',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('past_due', 'past_due'), ('unpaid', 'unpaid'), ('canceled', 'canceled'), ('incomplete', 'incomplete'), ('incomplete_expired', 'incomplete_expired'), ('trialing', 'trialing'), ('paused', 'paused')], max_length=50),
        ),
    ]
