# Generated by Django 3.0.8 on 2020-07-03 23:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_bookingchannelsync_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
