# Generated by Django 4.2.4 on 2023-11-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_account_validity_alter_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='current_plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
