# Generated by Django 3.0.8 on 2020-07-03 23:15

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Lodging = apps.get_model('core', 'Lodging')
    for row in Lodging.objects.all():
        row.uid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_lodging_uid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
