# Generated by Django 4.2.8 on 2023-12-28 14:53

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_activity_author_alter_activity_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='deposit_label',
        ),
        migrations.AddField(
            model_name='historicallodging',
            name='deposit_label',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('down_payment', 'Down payment')], default='deposit', max_length=30, verbose_name='deposit or down payment'),
        ),
        migrations.AddField(
            model_name='historicallodging',
            name='deposit_percent',
            field=models.IntegerField(default=30, verbose_name='deposit rate'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='deposit_label',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('down_payment', 'Down payment')], default='deposit', max_length=30, verbose_name='deposit or down payment'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='deposit_percent',
            field=models.IntegerField(default=30, verbose_name='deposit rate'),
        ),
    ]
