# Generated by Django 3.0.8 on 2020-07-04 01:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
