# Generated by Django 4.2.8 on 2024-01-05 16:25

from django.db import migrations, models


def convert_lodging_to_lodgings(apps, schema_editor):
    Booking = apps.get_model("core", "Booking")
    for booking in Booking.objects.all():
        booking.lodgings.add(booking.lodging)


def revert_lodging_from_lodgings(apps, schema_editor):
    Booking = apps.get_model("core", "Booking")
    for booking in Booking.objects.all():
        booking.lodging = booking.lodgings.first()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_remove_account_deposit_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guests_distribution",
            field=models.JSONField(blank=True, null=True, verbose_name="guests distribution"),
        ),
        migrations.AddField(
            model_name="booking",
            name="lodgings",
            field=models.ManyToManyField(to="core.lodging"),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="guests_distribution",
            field=models.JSONField(blank=True, null=True, verbose_name="guests distribution"),
        ),
        # migrations.AlterField(
        #     model_name='booking',
        #     name='lodging',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.lodging'),
        # ),
        migrations.RunPython(convert_lodging_to_lodgings, reverse_code=revert_lodging_from_lodgings),
        migrations.RemoveField(model_name="booking", name="lodging"),
        migrations.RemoveField(model_name="historicalbooking", name="lodging",),
    ]
