# Generated by Django 3.0.8 on 2020-07-03 23:15

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Booking = apps.get_model('core', 'Booking')
    for row in Booking.objects.all():
        row.uid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_booking_uid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
