# Generated by Django 4.2.8 on 2024-01-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_booking_guests_distribution_booking_lodgings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='grouped_bookings',
            field=models.BooleanField(default=False),
        ),
    ]
