# Generated by Django 4.2.8 on 2024-01-12 03:24
import logging

from django.db import migrations


def fill_guests_repartition_field(apps, schema_editor):
    Booking = apps.get_model("core", "Booking")
    for booking in Booking.objects.all():
        if not booking.lodgings.first():
            logging.warning("Booking without lodging: %s", booking)
            continue

        booking.guests_distribution = {
            booking.lodgings.first().id: {
                "adults": booking.adults,
                "children": booking.children,
                "babies": booking.babies,
            }
        }
        booking.save(update_fields=["guests_distribution"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_plan_grouped_bookings"),
    ]

    operations = [
        migrations.RunPython(fill_guests_repartition_field, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="booking",
            name="adults",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="babies",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="children",
        ),
        migrations.RemoveField(
            model_name="historicalbooking",
            name="adults",
        ),
        migrations.RemoveField(
            model_name="historicalbooking",
            name="babies",
        ),
        migrations.RemoveField(
            model_name="historicalbooking",
            name="children",
        ),
    ]
