# Generated by Django 3.0.8 on 2020-07-03 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
