# Generated by Django 3.0.8 on 2020-07-04 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_uuid_null'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingchannelsync',
            old_name='last_sync',
            new_name='last_import',
        ),
    ]
