# Generated by Django 4.2.8 on 2024-01-13 11:30

import django.db.models.deletion
from django.db import migrations, models


def set_account_field(apps, schema_editor):
    Booking = apps.get_model("core", "Booking")
    for booking in Booking.objects.all():
        booking.account = booking.lodgings.first().account
        booking.save(update_fields=["account"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_guests_repartition"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.account",
                verbose_name="account",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.account",
                verbose_name="account",
            ),
        ),
        migrations.RunPython(set_account_field),
        migrations.AlterField(
            model_name="booking",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
            ),
        ),
    ]
