# Generated by Django 4.2.8 on 2024-01-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_booking_account_historicalbooking_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure_details',
            field=models.CharField(blank=True, help_text='Check-out time, flight number, etc...', max_length=100, null=True, verbose_name='departure details'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='departure_details',
            field=models.CharField(blank=True, help_text='Check-out time, flight number, etc...', max_length=100, null=True, verbose_name='departure details'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_details',
            field=models.CharField(blank=True, help_text='Check-in time, flight number, etc...', max_length=100, null=True, verbose_name='arrival details'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='arrival_details',
            field=models.CharField(blank=True, help_text='Check-in time, flight number, etc...', max_length=100, null=True, verbose_name='arrival details'),
        ),
    ]
