# Generated by Django 3.0.8 on 2020-07-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200704_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingchannelsync',
            name='last_export',
            field=models.DateTimeField(blank=True, help_text='Last time the calendar has been successfully requested by remote channel.', null=True),
        ),
    ]
