# Generated by Django 3.0.8 on 2020-07-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_bookingchannelsync_last_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingchannelsync',
            name='last_import',
            field=models.DateTimeField(blank=True, help_text='Last time we imported remote calendar from channel.', null=True),
        ),
    ]
