# Generated by Django 4.2.8 on 2024-01-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_booking_departure_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallodging',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='registration number'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='registration number'),
        ),
    ]
