# Generated by Django 3.0.8 on 2020-07-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200704_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingchannel',
            options={'ordering': ['name'], 'verbose_name': 'Booking channel'},
        ),
        migrations.AlterModelOptions(
            name='lodging',
            options={'ordering': ['owner', 'rank'], 'verbose_name': 'Lodging'},
        ),
    ]
