# Generated by Django 4.2.8 on 2024-01-19 18:45

from django.db import migrations, models


def copy_tourist_tax_fields(apps, schema_editor):
    Booking = apps.get_model("core", "Booking")
    for booking in Booking.objects.all():
        booking.is_flat_rate_tourist_tax = booking.lodgings.first().is_flat_rate_tourist_tax
        booking.max_daily_tourist_tax = booking.lodgings.first().max_daily_tourist_tax
        booking.tourist_tax_included_in_payment = booking.lodgings.first().tourist_tax_included_in_payment
        booking.tourist_tax_rate = booking.lodgings.first().tourist_tax_rate

        booking.save(
            update_fields=[
                "is_flat_rate_tourist_tax",
                "max_daily_tourist_tax",
                "tourist_tax_rate",
                "tourist_tax_included_in_payment",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_historicallodging_registration_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_flat_rate_tourist_tax",
            field=models.BooleanField(default=True, verbose_name="flat rate tourist tax"),
        ),
        migrations.AddField(
            model_name="booking",
            name="max_daily_tourist_tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="max daily tourist tax"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="tourist_tax_included_in_payment",
            field=models.BooleanField(
                default=True,
                help_text="An hidden feature for internal use only",
                verbose_name="tourist tax included in payment",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="tourist_tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="tourist tax rate"
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="is_flat_rate_tourist_tax",
            field=models.BooleanField(default=True, verbose_name="flat rate tourist tax"),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="max_daily_tourist_tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="max daily tourist tax"
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="tourist_tax_included_in_payment",
            field=models.BooleanField(
                default=True,
                help_text="An hidden feature for internal use only",
                verbose_name="tourist tax included in payment",
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="tourist_tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="tourist tax rate"
            ),
        ),
        migrations.RunPython(copy_tourist_tax_fields),
    ]
