# Generated by Django 3.0.8 on 2020-08-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_contract_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='description',
            field=models.TextField(blank=True, help_text='Used by contracts generation', verbose_name='description'),
        ),
    ]
