# Generated by Django 5.2.17 on 2026-09-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_constance_pickle_to_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holidays',
        ),
    ]
