# Generated by Django 3.0.8 on 2020-08-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_lodging_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract'},
        ),
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name': 'Contract template'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf',
            field=models.FilePathField(blank=True, null=True, path='/Users/ricard/develop/location/files/contracts'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='signed'),
        ),
    ]
