# Generated by Django 5.2.17 on 2026-09-10 19:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_delete_holidays"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("color", models.CharField(default="#3788d8", max_length=7, verbose_name="color")),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order, and the season kept when two date ranges overlap (lowest wins)",
                        verbose_name="rank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Season",
                "ordering": ["calendar", "rank", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="seasonalvariation",
            name="pricing",
        ),
        migrations.AddField(
            model_name="booking",
            name="price_details",
            field=models.JSONField(
                blank=True,
                help_text="Snapshot of the price breakdown (per-night rates and adjustments) from the pricing engine",
                null=True,
                verbose_name="price details",
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="price_details",
            field=models.JSONField(
                blank=True,
                help_text="Snapshot of the price breakdown (per-night rates and adjustments) from the pricing engine",
                null=True,
                verbose_name="price details",
            ),
        ),
        migrations.AddField(
            model_name="historicallodging",
            name="min_nights",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="minimum nights"),
        ),
        migrations.AddField(
            model_name="historicallodging",
            name="monthly_discount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Applied when the stay is at least 28 nights (supersedes the weekly discount)",
                max_digits=5,
                null=True,
                verbose_name="monthly discount rate",
            ),
        ),
        migrations.AddField(
            model_name="historicallodging",
            name="weekly_discount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Applied when the stay is at least 7 nights",
                max_digits=5,
                null=True,
                verbose_name="weekly discount rate",
            ),
        ),
        migrations.AddField(
            model_name="lodging",
            name="min_nights",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="minimum nights"),
        ),
        migrations.AddField(
            model_name="lodging",
            name="monthly_discount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Applied when the stay is at least 28 nights (supersedes the weekly discount)",
                max_digits=5,
                null=True,
                verbose_name="monthly discount rate",
            ),
        ),
        migrations.AddField(
            model_name="lodging",
            name="weekly_discount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Applied when the stay is at least 7 nights",
                max_digits=5,
                null=True,
                verbose_name="weekly discount rate",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalPricingAdjustment",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed amount")],
                        default="percent",
                        max_length=10,
                        verbose_name="adjustment type",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Negative for a discount, positive for a surcharge. Percent points or currency amount.",
                        max_digits=20,
                        verbose_name="value",
                    ),
                ),
                ("min_nights", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="minimum nights")),
                ("max_nights", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="maximum nights")),
                (
                    "min_days_before_arrival",
                    models.IntegerField(
                        blank=True,
                        help_text="Early booking discount.",
                        null=True,
                        verbose_name="minimum days before arrival",
                    ),
                ),
                (
                    "max_days_before_arrival",
                    models.IntegerField(
                        blank=True,
                        help_text="Last minute discount.",
                        null=True,
                        verbose_name="maximum days before arrival",
                    ),
                ),
                ("stay_begin", models.DateField(blank=True, null=True, verbose_name="stay window start")),
                ("stay_end", models.DateField(blank=True, null=True, verbose_name="stay window end")),
                ("booking_begin", models.DateField(blank=True, null=True, verbose_name="booking window start")),
                ("booking_end", models.DateField(blank=True, null=True, verbose_name="booking window end")),
                (
                    "applicable_weekdays",
                    models.JSONField(
                        blank=True,
                        help_text="List of weekday numbers (Monday=0). Empty applies to the whole stay.",
                        null=True,
                        verbose_name="applicable weekdays",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower is applied first.", verbose_name="priority"
                    ),
                ),
                (
                    "stackable",
                    models.BooleanField(
                        default=True,
                        help_text="If off, no lower-priority rule is applied after this one.",
                        verbose_name="stackable",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.account",
                        verbose_name="account",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lodging",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Empty means the rule applies to every lodging of the account.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.lodging",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pricing adjustment",
                "verbose_name_plural": "historical Pricing adjustments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSeasonCalendar",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.account",
                        verbose_name="account",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Season calendar",
                "verbose_name_plural": "historical Season calendars",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PricingAdjustment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed amount")],
                        default="percent",
                        max_length=10,
                        verbose_name="adjustment type",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Negative for a discount, positive for a surcharge. Percent points or currency amount.",
                        max_digits=20,
                        verbose_name="value",
                    ),
                ),
                ("min_nights", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="minimum nights")),
                ("max_nights", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="maximum nights")),
                (
                    "min_days_before_arrival",
                    models.IntegerField(
                        blank=True,
                        help_text="Early booking discount.",
                        null=True,
                        verbose_name="minimum days before arrival",
                    ),
                ),
                (
                    "max_days_before_arrival",
                    models.IntegerField(
                        blank=True,
                        help_text="Last minute discount.",
                        null=True,
                        verbose_name="maximum days before arrival",
                    ),
                ),
                ("stay_begin", models.DateField(blank=True, null=True, verbose_name="stay window start")),
                ("stay_end", models.DateField(blank=True, null=True, verbose_name="stay window end")),
                ("booking_begin", models.DateField(blank=True, null=True, verbose_name="booking window start")),
                ("booking_end", models.DateField(blank=True, null=True, verbose_name="booking window end")),
                (
                    "applicable_weekdays",
                    models.JSONField(
                        blank=True,
                        help_text="List of weekday numbers (Monday=0). Empty applies to the whole stay.",
                        null=True,
                        verbose_name="applicable weekdays",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower is applied first.", verbose_name="priority"
                    ),
                ),
                (
                    "stackable",
                    models.BooleanField(
                        default=True,
                        help_text="If off, no lower-priority rule is applied after this one.",
                        verbose_name="stackable",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
                    ),
                ),
                (
                    "lodging",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty means the rule applies to every lodging of the account.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_adjustments",
                        to="core.lodging",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing adjustment",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="LodgingSeasonRate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nightly_rate", models.DecimalField(decimal_places=2, max_digits=20, verbose_name="nightly rate")),
                (
                    "weekend_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Friday and Saturday nights. Empty means the nightly rate is used.",
                        max_digits=20,
                        null=True,
                        verbose_name="weekend rate",
                    ),
                ),
                (
                    "min_nights",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Empty means the lodging default is used.",
                        null=True,
                        verbose_name="minimum nights",
                    ),
                ),
                (
                    "lodging",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="season_rates", to="core.lodging"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lodging_rates", to="core.season"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lodging season rate",
                "ordering": ["lodging", "season"],
                "unique_together": {("lodging", "season")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalLodgingSeasonRate",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("nightly_rate", models.DecimalField(decimal_places=2, max_digits=20, verbose_name="nightly rate")),
                (
                    "weekend_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Friday and Saturday nights. Empty means the nightly rate is used.",
                        max_digits=20,
                        null=True,
                        verbose_name="weekend rate",
                    ),
                ),
                (
                    "min_nights",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Empty means the lodging default is used.",
                        null=True,
                        verbose_name="minimum nights",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lodging",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.lodging",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Lodging season rate",
                "verbose_name_plural": "historical Lodging season rates",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SeasonCalendar",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.account", verbose_name="account"
                    ),
                ),
            ],
            options={
                "verbose_name": "Season calendar",
                "ordering": ["name"],
                "unique_together": {("account", "name")},
            },
        ),
        migrations.AddField(
            model_name="season",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="seasons", to="core.seasoncalendar"
            ),
        ),
        migrations.AddField(
            model_name="historicallodging",
            name="season_calendar",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Shared season calendar driving seasonal rates for this lodging",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.seasoncalendar",
            ),
        ),
        migrations.AddField(
            model_name="lodging",
            name="season_calendar",
            field=models.ForeignKey(
                blank=True,
                help_text="Shared season calendar driving seasonal rates for this lodging",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lodgings",
                to="core.seasoncalendar",
            ),
        ),
        migrations.CreateModel(
            name="SeasonDateRange",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("begin_date", models.DateField(verbose_name="first night")),
                ("end_date", models.DateField(verbose_name="last night")),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="date_ranges", to="core.season"
                    ),
                ),
            ],
            options={
                "verbose_name": "Season date range",
                "ordering": ["begin_date"],
            },
        ),
        migrations.DeleteModel(
            name="Pricing",
        ),
        migrations.DeleteModel(
            name="SeasonalVariation",
        ),
    ]
