# Generated by Django 3.0.9 on 2020-09-08 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_pdf_nullable_on_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_card', 'Bank card'), ('check', 'Check'), ('transfer', 'Transfer'), ('paypal', 'PayPal'), ('vouchers', 'Holiday vouchers'), ('other', 'Other')], max_length=30, verbose_name='Payment method')),
                ('date', models.DateField(verbose_name='Payment date')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Booking')),
            ],
        ),
    ]
