# Generated by Django 3.0.9 on 2020-09-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='commission fees'),
        ),
    ]
