# Generated by Django 3.1.1 on 2020-09-21 11:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_creation_date_to_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf',
            field=models.FilePathField(blank=True, null=True, path=core.models.contracts_path),
        ),
    ]
