# Generated by Django 3.1.1 on 2020-09-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_fix_contracts_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
