# Generated by Django 3.1.1 on 2020-10-01 02:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_Alter field pdf on contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='logo',
            field=models.ImageField(blank=True, upload_to=core.models.user_directory_path, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='signature',
            field=models.ImageField(blank=True, upload_to=core.models.user_directory_path, verbose_name='signature'),
        ),
    ]
