# Generated by Django 3.1.1 on 2020-12-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_Alter fields logo and signature on owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='shown',
            field=models.BooleanField(default=True, verbose_name='shown'),
        ),
    ]
