# Generated by Django 3.1.4 on 2020-12-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='included_in_booking',
            field=models.BooleanField(default=False, help_text='If true, the price of this option is included in booking price and not displayed separately', verbose_name='included in booking'),
        ),
        migrations.AddField(
            model_name='service',
            name='included_in_booking',
            field=models.BooleanField(default=False, help_text='If true, the price of this option is included in booking price and not displayed separately', verbose_name='included in booking'),
        ),
    ]
