# Generated by Django 3.1.4 on 2020-12-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_included_in_booking_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='is_flat_rate',
            field=models.BooleanField(default=False, help_text='Use flat rate price instead of daily price computation', verbose_name='flat rate?'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_flat_rate',
            field=models.BooleanField(default=False, help_text='Use flat rate price instead of daily price computation', verbose_name='flat rate?'),
        ),
    ]
