# Generated by Django 3.1.4 on 2020-12-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_Add field is_flat_rate to service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('reference',), 'verbose_name': 'Service'},
        ),
        migrations.AlterField(
            model_name='bookedservice',
            name='quantity',
            field=models.SmallIntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='service',
            name='quantity',
            field=models.SmallIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='quantity',
            field=models.SmallIntegerField(default=1, verbose_name='quantity'),
        ),
    ]
