# Generated by Django 3.1.4 on 2021-02-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_option_quantity_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
    ]
