# Generated by Django 3.1.4 on 2021-05-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingchannelsync',
            name='last_import_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
