# Generated by Django 3.1.4 on 2021-06-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_bookingchannelsync_last_import_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='not_included_in_price',
            field=models.BooleanField(default=False, help_text='Service not included in current booking price. Maybe provided by external partner...', verbose_name='not included in price'),
        ),
        migrations.AddField(
            model_name='service',
            name='not_included_in_price',
            field=models.BooleanField(default=False, help_text='Service not included in current booking price. Maybe provided by external partner...', verbose_name='not included in price'),
        ),
    ]
