# Generated by Django 3.1.4 on 2021-06-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add field not_included_in_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallodging',
            name='tourist_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='tourist tax'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='tourist_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='tourist tax'),
        ),
    ]
