# Generated by Django 3.1.4 on 2021-07-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add tourist_tax field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
