# Generated by Django 3.2.6 on 2021-08-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_increase_contract_filename_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date']},
        ),
    ]
