# Generated by Django 3.2.6 on 2021-08-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_payment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalservice',
            old_name='unit_price_ht',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='unit_price_ht',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='unit price VAT incl.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='unit price VAT incl.'),
        ),
    ]
