# Generated by Django 3.2.6 on 2021-08-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_rename Service field unit_price_ht to unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallodging',
            name='cleaning_fee',
        ),
        migrations.RemoveField(
            model_name='lodging',
            name='cleaning_fee',
        ),
    ]
