# Generated by Django 4.2.4 on 2023-11-25 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('klass', models.CharField(help_text='Example: notifier.backends.EmailBackend', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=True)),
                ('default_notify', models.BooleanField(default=True, help_text='Default notification state')),
                ('backends', models.ManyToManyField(blank=True, to='notifier.backend')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Description displayed', null=True)),
                ('path', models.CharField(blank=True, help_text='Page to redirect (path part of the url)', max_length=255, null=True)),
                ('success', models.BooleanField()),
                ('read', models.BooleanField(default=False)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.backend')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPrefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('notify', models.BooleanField(default=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.backend')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification', 'backend')},
            },
        ),
        migrations.CreateModel(
            name='GroupPrefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('notify', models.BooleanField(default=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.backend')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.notification')),
            ],
            options={
                'unique_together': {('group', 'notification', 'backend')},
            },
        ),
    ]
