import os
import tempfile

import pdfkit
from django.conf import settings
from django.utils.translation import gettext


def generate_pdf(content: str, full_path: str, add_watermark: bool):
    os.makedirs(os.path.split(full_path)[0], exist_ok=True)
    config = pdfkit.configuration(wkhtmltopdf=settings.WKHTMLTOPDF_PATH)
    options = {
        "encoding": "UTF-8",
        "page-size": "A4",
        "margin-top": "20mm",
        "margin-bottom": "20mm",
        "margin-right": "20mm",
        "margin-left": "20mm",
        "footer-right": "Page [page] sur [topage]",
        "footer-font-size": "9",
        "custom-header": [("Accept-Encoding", "gzip")],
        "enable-local-file-access": False,
        "no-outline": None,
    }

    temp = tempfile.NamedTemporaryFile(delete=True, suffix=".html")
    if add_watermark:
        with open(temp.name, "w", encoding="utf-8-sig") as f:
            f.write(
                '<!DOCTYPE HTML><footer style="text-align: center; font-style: italic;"><span>'
                + gettext("Generated by the free edition of Tiloc (https://tiloc.fr)")
                + "</span></footer>"
            )
        options.update(
            {
                "footer-html": temp.name,
            }
        )
    print(options)

    pdfkit.from_string(content, full_path, configuration=config, options=options)
