export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";
export const AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED";

// generic actions
export const REQUEST = name => name + "_REQUEST";
export const SUCCESS = name => name + "_SUCCESS";
export const FAILURE = name => name + "_FAILURE";

export const FETCH_BOOKINGS = "FETCH_BOOKINGS";
export const CREATE_BOOKING = "CREATE_BOOKING";
export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";

export const FETCH_BOOKING_STATUSES = "FETCH_BOOKING_STATUSES";

export const FETCH_BOOKING_CHANNELS = "FETCH_BOOKING_CHANNELS";

export const FETCH_SERVICES = "FETCH_SERVICES";

export const FETCH_LODGINGS = "FETCH_LODGINGS";

export const FETCH_OWNERS = "FETCH_OWNERS";

export const FETCH_CONTRACTS = "FETCH_CONTRACTS";
export const GET_OR_CREATE_CONTRACT = "GET_OR_CREATE_CONTRACT";
export const GENERATE_CONTRACT = "GENERATE_CONTRACT";
export const UPDATE_CONTRACT = "UPDATE_CONTRACT";
export const DELETE_CONTRACT = "DELETE_CONTRACT";

export const FETCH_CONTRACT_TEMPLATES = "FETCH_CONTRACT_TEMPLATES";
export const GET_CONTRACT_TEMPLATE = "GET_CONTRACT_TEMPLATE";
export const CREATE_CONTRACT_TEMPLATE = "CREATE_CONTRACT_TEMPLATE";
export const UPDATE_CONTRACT_TEMPLATE = "UPDATE_CONTRACT_TEMPLATE";
export const DELETE_CONTRACT_TEMPLATE = "DELETE_CONTRACT_TEMPLATE";
