# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Dossier(models.Model):
    id = models.AutoField(primary_key=True, db_column='dossier_id')
    # groupe = models.IntegerField(blank=True, null=True, db_column='dossier_groupe')
    client_nom = models.CharField(blank=True, null=True, db_column='dossier_client_nom', max_length=256)
    client_contact = models.CharField(blank=True, null=True, db_column='dossier_client_contact', max_length=256)
    client_adresse = models.CharField(blank=True, null=True, db_column='dossier_client_adresse', max_length=256)
    logement_id = models.IntegerField(blank=True, null=True, db_column='dossier_logement_id')
    date_debut = models.DateField(blank=True, null=True, db_column='dossier_date_debut')
    date_fin = models.DateField(blank=True, null=True, db_column='dossier_date_fin')
    # duree = models.IntegerField(blank=True, null=True, db_column='dossier_duree')
    # statut = models.IntegerField(db_column='dossier_statut')
    # nb_adulte = models.IntegerField(blank=True, null=True, db_column='dossier_nb_adulte')
    # nb_enfant = models.IntegerField(blank=True, null=True, db_column='dossier_nb_enfant')
    # nb_moins13 = models.IntegerField(blank=True, null=True, db_column='dossier_nb_moins13')
    restauration = models.CharField(db_column='dossier_restauration', max_length=256)
    # prix_jour = models.DecimalField(max_digits=10, decimal_places=2, db_column='dossier_prix_jour')
    # prix_tot = models.DecimalField(max_digits=10, decimal_places=2, db_column='dossier_prix_tot')
    forfait = models.TextField(blank=True, null=True, db_column='dossier_forfait')
    arrhes = models.TextField(blank=True, null=True, db_column='dossier_arrhes')
    info = models.TextField(blank=True, null=True, db_column='dossier_info')
    # fact_id = models.IntegerField(blank=True, null=True, db_column='dossier_fact_id')
    fact_date = models.DateField(blank=True, null=True, db_column='dossier_fact_date')
    # motif = models.IntegerField(blank=True, null=True, db_column='dossier_motif')
    # proprietaire_id = models.IntegerField(db_column='dossier_proprietaire_id')
    # contrat = models.BinaryField(blank=True, null=True, db_column='dossier_contrat')
    # contrat_date = models.DateField(blank=True, null=True, db_column='dossier_contrat_date')
    # cond_part = models.CharField(blank=True, null=True, db_column='dossier_cond_part', max_length=256)
    # option1_id = models.IntegerField(blank=True, null=True, db_column='dossier_option1_id')
    # option1_quantite = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='dossier_option1_quantite')
    # option2_id = models.IntegerField(blank=True, null=True, db_column='dossier_option2_id')
    # option2_quantite = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='dossier_option2_quantite')
    # option3_id = models.IntegerField(blank=True, null=True, db_column='dossier_option3_id')
    # option3_quantite = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='dossier_option3_quantite')
    # option4_id = models.IntegerField(blank=True, null=True, db_column='dossier_option4_id')
    # option4_quantite = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='dossier_option4_quantite')
    # option5_id = models.IntegerField(blank=True, null=True, db_column='dossier_option5_id')
    # option5_quantite = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='dossier_option5_quantite')
    # option6_id = models.IntegerField(blank=True, null=True, db_column='dossier_option6_id')
    # option6_quantite = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='dossier_option6_quantite')
    # option7_id = models.IntegerField(blank=True, null=True, db_column='dossier_option7_id')
    # option7_quantite = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='dossier_option7_quantite')
    # option8_id = models.IntegerField(blank=True, null=True, db_column='dossier_option8_id')
    # option8_quantite = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='dossier_option8_quantite')
    # option9_id = models.IntegerField(blank=True, null=True, db_column='dossier_option9_id')
    # option9_quantite = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='dossier_option9_quantite')
    # option_tot = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='dossier_option_tot')
    # caution = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='dossier_caution')
    # tarif_info_bulle = models.TextField(blank=True, null=True, db_column='dossier_tarif_info_bulle')
    # tarif_fact_items = models.TextField(blank=True, null=True, db_column='dossier_tarif_fact_items')
    # tarif_jour = models.DecimalField(max_digits=10, decimal_places=5, db_column='dossier_tarif_jour')
    # tarif_we = models.DecimalField(max_digits=10, decimal_places=5, db_column='dossier_tarif_we')
    # tarif_semaine = models.DecimalField(max_digits=10, decimal_places=5, db_column='dossier_tarif_semaine')
    # search = models.TextField(blank=True, null=True, db_column='dossier_search')

    class Meta:
        managed = False
        db_table = 'dossier'


class Facture(models.Model):
    id = models.AutoField(primary_key=True, db_column='fact_id')
    ref = models.CharField(blank=True, null=True, max_length=50, db_column='fact_ref')
    date = models.DateField(blank=True, null=True, db_column='fact_date')
    commande_date = models.DateField(blank=True, null=True, db_column='fact_commande_date')
    devis_date = models.DateField(blank=True, null=True, db_column='fact_devis_date')
    paie_date = models.DateField(blank=True, null=True, db_column='fact_paie_date')
    client_nom = models.CharField(blank=True, null=True, max_length=256, db_column='fact_client_nom')
    client_adresse = models.TextField(blank=True, null=True, db_column='fact_client_adresse')
    items = models.TextField(blank=True, null=True, db_column='fact_items')
    montant_ht = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='fact_montant_ht')
    montant_tva = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='fact_montant_tva')
    montant_ttc = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='fact_montant_ttc')
    acompte = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='fact_acompte')
    paie1 = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='fact_paie1')
    apayer = models.DecimalField(max_digits=10, decimal_places=5, blank=True, null=True, db_column='fact_apayer')
    cond = models.CharField(blank=True, null=True, max_length=256, db_column='fact_cond')
    commentaire = models.TextField(blank=True, null=True, db_column='fact_commentaire')
    notva = models.TextField(blank=True, null=True, db_column='fact_notva')
    statut = models.CharField(blank=True, null=True, max_length=30, db_column='fact_statut')
    pmod_acompte = models.CharField(blank=True, null=True, max_length=50, db_column='fact_pmod_acompte')
    pmod_paie1 = models.CharField(blank=True, null=True, max_length=50, db_column='fact_pmod_paie1')
    descriptif = models.CharField(blank=True, null=True, max_length=256, db_column='fact_descriptif')
    proprietaire_id = models.IntegerField(db_column='fact_proprietaire_id')

    class Meta:
        managed = False
        db_table = 'facture'


class Logement(models.Model):
    id = models.AutoField(primary_key=True, db_column='logement_id')
    ordre = models.IntegerField(db_column='logement_ordre')
    nom = models.CharField(blank=True, null=True, max_length=256, db_column='logement_nom')
    adresse = models.CharField(blank=True, null=True, max_length=256, db_column='logement_adresse')
    prix_base = models.DecimalField(max_digits=10, decimal_places=2, db_column='logement_prix_base')
    forfait = models.TextField(blank=True, null=True, db_column='logement_forfait')
    prix_forfait = models.DecimalField(max_digits=10, decimal_places=2, db_column='logement_prix_forfait')
    depot = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, db_column='logement_depot')
    info = models.CharField(blank=True, null=True, max_length=256, db_column='logement_info')
    statut = models.CharField(max_length=50, db_column='logement_statut')
    proprietaire_id = models.IntegerField(db_column='logement_proprietaire_id')
    etat_des = models.TextField(blank=True, null=True, db_column='logement_etat_des')
    prix_we = models.DecimalField(max_digits=10, decimal_places=2, db_column='logement_prix_we')
    duree_sejour = models.IntegerField(blank=True, null=True, db_column='logement_duree_sejour')
    nb_base = models.IntegerField(blank=True, null=True, db_column='logement_nb_base')
    prix_supp = models.DecimalField(max_digits=10, decimal_places=2, db_column='logement_prix_supp')
    tarif_id = models.IntegerField(blank=True, null=True, db_column='logement_tarif_id')
    service_id = models.IntegerField(blank=True, null=True, db_column='logement_service_id')
    resa_info = models.TextField(blank=True, null=True, db_column='logement_resa_info')
    internet_masquer = models.TextField(blank=True, null=True, db_column='logement_internet_masquer')

    class Meta:
        managed = False
        db_table = 'logement'


class Proprietaire(models.Model):
    id = models.AutoField(primary_key=True, db_column='proprietaire_id')
    statut = models.CharField(max_length=50, db_column='proprietaire_statut')
    master = models.BooleanField(db_column='proprietaire_master')
    nom = models.CharField(blank=True, null=True, max_length=256, db_column='proprietaire_nom')
    nom_gite = models.CharField(blank=True, null=True, max_length=256, db_column='proprietaire_nom_gite')
    email = models.CharField(blank=True, null=True, max_length=256, db_column='proprietaire_email')
    contact = models.CharField(blank=True, null=True, max_length=256, db_column='proprietaire_contact')
    adresse = models.TextField(blank=True, null=True, db_column='proprietaire_adresse')
    legal = models.CharField(blank=True, null=True, max_length=256, db_column='proprietaire_legal')
    fact_paie = models.CharField(blank=True, null=True, max_length=256, db_column='proprietaire_fact_paie')
    fact_cond = models.CharField(blank=True, null=True, max_length=256, db_column='proprietaire_fact_cond')
    notva = models.BooleanField(db_column='proprietaire_notva')
    tva1 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, db_column='proprietaire_tva1')
    tva_detail = models.NullBooleanField(blank=True, null=True, db_column='proprietaire_tva_detail')
    txad = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, db_column='proprietaire_txad')
    txrd = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, db_column='proprietaire_txrd')
    note = models.CharField(max_length=256, db_column='proprietaire_note')
    acompte = models.CharField(max_length=256, db_column='proprietaire_acompte')
    logo_name = models.CharField(max_length=256, db_column='proprietaire_logo_name')
    signature_name = models.CharField(max_length=256, db_column='proprietaire_signature_name')
    aff_semaine = models.NullBooleanField(db_column='proprietaire_aff_semaine')

    class Meta:
        managed = False
        db_table = 'proprietaire'


class Service(models.Model):
    service_id = models.AutoField(primary_key=True)
    service_reference = models.CharField(blank=True, null=True, max_length=100)
    service_categorie = models.CharField(blank=True, null=True, max_length=100)
    service_designation = models.CharField(blank=True, null=True, max_length=256)
    service_quantite = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    service_puht = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    service_tva = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    service_auto = models.TextField(blank=True, null=True)
    service_auto_contrat = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'service'


class Variable(models.Model):
    id = models.AutoField(primary_key=True, db_column='variable_id')
    stamp = models.CharField(blank=True, null=True, max_length=100, db_column='variable_stamp')
    devise = models.CharField(max_length=10, db_column='variable_devise')
    statut1 = models.CharField(max_length=100, db_column='variable_statut1')
    statut10 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut10')
    statut20 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut20')
    statut30 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut30')
    statut40 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut40')
    statut50 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut50')
    statut60 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut60')
    statut61 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut61')
    statut62 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut62')
    statut63 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut63')
    statut64 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut64')
    statut65 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut65')
    statut66 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut66')
    statut67 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut67')
    statut68 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut68')
    statut69 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut69')
    statut70 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut70')
    statut71 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut71')
    statut72 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut72')
    statut73 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut73')
    statut74 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_statut74')
    couleur1 = models.CharField(max_length=100, db_column='variable_couleur1')
    couleur10 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_couleur10')
    couleur20 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_couleur20')
    couleur30 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_couleur30')
    couleur40 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_couleur40')
    couleur50 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_couleur50')
    couleur60 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_couleur60')
    couleur61 = models.CharField(max_length=100, db_column='variable_couleur61')
    couleur62 = models.CharField(max_length=100, db_column='variable_couleur62')
    couleur63 = models.CharField(max_length=100, db_column='variable_couleur63')
    couleur64 = models.CharField(max_length=100, db_column='variable_couleur64')
    couleur65 = models.CharField(max_length=100, db_column='variable_couleur65')
    couleur66 = models.CharField(max_length=100, db_column='variable_couleur66')
    couleur67 = models.CharField(max_length=100, db_column='variable_couleur67')
    couleur68 = models.CharField(max_length=100, db_column='variable_couleur68')
    couleur69 = models.CharField(max_length=100, db_column='variable_couleur69')
    couleur70 = models.CharField(max_length=100, db_column='variable_couleur70')
    couleur71 = models.CharField(max_length=100, db_column='variable_couleur71')
    couleur72 = models.CharField(max_length=100, db_column='variable_couleur72')
    couleur73 = models.CharField(max_length=100, db_column='variable_couleur73')
    couleur74 = models.CharField(max_length=100, db_column='variable_couleur74')
    ab = models.CharField(blank=True, null=True, max_length=100, db_column='variable_ab')
    statut_paye_auto = models.BooleanField(db_column='variable_statut_paye_auto')
    affich_semaine = models.NullBooleanField(blank=True, null=True, db_column='variable_affich_semaine')
    categorie1 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie1')
    categorie2 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie2')
    categorie3 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie3')
    categorie4 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie4')
    categorie5 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie5')
    categorie6 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie6')
    categorie7 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie7')
    categorie8 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie8')
    categorie9 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie9')
    categorie10 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie10')
    categorie11 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie11')
    categorie12 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie12')
    categorie13 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie13')
    categorie14 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie14')
    categorie15 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie15')
    categorie16 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie16')
    categorie17 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie17')
    categorie18 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie18')
    categorie19 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie19')
    categorie20 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_categorie20')
    nb_mois_affich = models.IntegerField(db_column='variable_nb_mois_affich')
    motif1 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif1')
    motif2 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif2')
    motif3 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif3')
    motif4 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif4')
    motif5 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif5')
    motif6 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif6')
    motif7 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif7')
    motif8 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif8')
    motif9 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif9')
    motif10 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif10')
    motif11 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif11')
    motif12 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif12')
    motif13 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif13')
    motif14 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif14')
    motif15 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif15')
    motif16 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif16')
    motif17 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif17')
    motif18 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif18')
    motif19 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif19')
    motif20 = models.CharField(blank=True, null=True, max_length=100, db_column='variable_motif20')
    pmod = models.TextField(blank=True, null=True, db_column='variable_pmod')
    contrat_adresse = models.TextField(blank=True, null=True, db_column='variable_contrat_adresse')
    contrat_cond_gen = models.TextField(blank=True, null=True, db_column='variable_contrat_cond_gen')
    contrat_cond_part = models.CharField(blank=True, null=True, max_length=256, db_column='variable_contrat_cond_part')
    contrat_dossier_part = models.TextField(blank=True, null=True, db_column='variable_contrat_dossier_part')
    contrat_logo = models.BooleanField(blank=True, null=True, db_column='variable_contrat_logo')
    contrat_options = models.TextField(blank=True, null=True, db_column='variable_contrat_options')
    contrat_solde_affich = models.TextField(blank=True, null=True, db_column='variable_contrat_solde_affich')
    contrat_solde_text = models.CharField(blank=True, null=True, max_length=100, db_column='variable_contrat_solde_text')
    contrat_nb_affich = models.TextField(blank=True, null=True, db_column='variable_contrat_nb_affich')
    contrat_nuite_affich = models.TextField(blank=True, null=True, db_column='variable_contrat_nuite_affich')
    contrat_ville = models.CharField(blank=True, null=True, max_length=100, db_column='variable_contrat_ville')
    contrat_annexe_texte = models.TextField(db_column='variable_contrat_annexe_texte')
    contrat_caution_lib = models.CharField(max_length=100, db_column='variable_contrat_caution_lib')
    contrat_caution_texte = models.TextField(blank=True, null=True, db_column='variable_contrat_caution_texte')
    contrat_caution_mode = models.TextField(blank=True, null=True, db_column='variable_contrat_caution_mode')
    contrat_caution_prc = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, db_column='variable_contrat_caution_prc')
    contrat_police_print = models.IntegerField(db_column='variable_contrat_police_print')
    contrat_police_pdf = models.IntegerField(db_column='variable_contrat_police_pdf')
    arrhes_mode = models.TextField(blank=True, null=True, db_column='variable_arrhes_mode')
    arrhes_prc = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, db_column='variable_arrhes_prc')
    internet_pers = models.TextField(blank=True, null=True, db_column='variable_internet_pers')
    internet10 = models.TextField(blank=True, null=True, db_column='variable_internet10')
    internet20 = models.TextField(blank=True, null=True, db_column='variable_internet20')
    internet30 = models.TextField(blank=True, null=True, db_column='variable_internet30')
    internet40 = models.TextField(blank=True, null=True, db_column='variable_internet40')
    internet50 = models.TextField(blank=True, null=True, db_column='variable_internet50')
    internet60 = models.TextField(blank=True, null=True, db_column='variable_internet60')
    couleur_internet_li = models.CharField(blank=True, null=True, max_length=100, db_column='variable_couleur_internet_li')
    couleur_internet_re = models.CharField(blank=True, null=True, max_length=100, db_column='variable_couleur_internet_re')
    cle_secrete = models.CharField(blank=True, null=True, max_length=100, db_column='variable_cle_secrete')
    demi_journee_internet = models.TextField(blank=True, null=True, db_column='variable_demi_journee_internet')
    reg = models.CharField(blank=True, null=True, max_length=100, db_column='variable_reg')
    logo_position = models.TextField(blank=True, null=True, db_column='variable_logo_position')
    lib_adulte = models.CharField(max_length=100, db_column='variable_lib_adulte')
    lib_enfant = models.CharField(max_length=100, db_column='variable_lib_enfant')
    lib_autre = models.CharField(max_length=100, db_column='variable_lib_autre')
    planning_repete = models.TextField(blank=True, null=True, db_column='variable_planning_repete')
    police_print = models.IntegerField(db_column='variable_police_print')
    police_pdf = models.IntegerField(db_column='variable_police_pdf')
    sauv_internet = models.TextField(blank=True, null=True, db_column='variable_sauv_internet')
    last_sauv_internet = models.IntegerField(blank=True, null=True, db_column='variable_last_sauv_internet')
    resa_duree_min = models.IntegerField(blank=True, null=True, db_column='variable_resa_duree_min')
    resa_jour_arrivee = models.IntegerField(blank=True, null=True, db_column='variable_resa_jour_arrivee')
    resa_texte_recherche = models.CharField(blank=True, null=True, max_length=100, db_column='variable_resa_texte_recherche')
    resa_masquer_tarif = models.IntegerField(blank=True, null=True, db_column='variable_resa_masquer_tarif')
    sauvegarde_type = models.TextField(blank=True, null=True, db_column='variable_sauvegarde_type')
    logement_internet = models.TextField(blank=True, null=True, db_column='variable_logement_internet')
    liste_clients = models.IntegerField(blank=True, null=True, db_column='variable_liste_clients')

    class Meta:
        managed = False
        db_table = 'variable'
