"""
Django settings for location project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import logging
import os
import sys
from datetime import timedelta

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from my_django_tweaks.logging_config import configure_logging
from smartconfigparser import Config

from . import __version__

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_DIR = os.path.join(BASE_DIR, "config")
os.makedirs(CONFIG_DIR, exist_ok=True)
CONFIG_FILE = os.path.join(CONFIG_DIR, "config.ini")

config = Config()
config.read(CONFIG_FILE)

LOG_DIR = os.path.join(BASE_DIR, "log")
os.makedirs(LOG_DIR, exist_ok=True)

BACKUP_DIR = os.path.join(BASE_DIR, "backup")
os.makedirs(BACKUP_DIR, exist_ok=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"
ENV = os.environ.get("APP_ENV", DEBUG and "dev" or "prod")
UNITTEST = "test" in sys.argv or "pytest" in sys.modules
IS_DEMO = config.getboolean("APP", "IS_DEMO", False)

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = config.get("APP", "SECRET_KEY")  # '7rf!%(5w-db9ln+0dcdvv))!_d!e1c33-8v7^1gqe$t@7!=b4!'
except Exception:
    print("SECRET_KEY not found! Generating a new one...", file=sys.stderr)
    import random

    SECRET_KEY = "".join([random.choice("abcdefghijklmnopqrstuvwxyz0123456789!@#$^&*(-_=+)") for i in range(50)])
    config.set("APP", "SECRET_KEY", SECRET_KEY)
    f = open(CONFIG_FILE, "wt")
    config.write(f)
    f.close()

LOGGING_CONFIG = None  # disable log configuration by Django
DEFAULT_LOG_FORMAT = "%(name)-12s: %(asctime)s %(levelname)-8s [%(threadName)s] %(message)s"

LOGGING = configure_logging("location", CONFIG_DIR, LOG_DIR, DEFAULT_LOG_FORMAT, UNITTEST)

if ENV not in ["dev", "prod"]:
    logging.critical("Bad value for APP_ENV environment settings: %s", ENV)

logging.info("Starting django application (%s) %s %s", ENV, sys.argv[1:], DEBUG and "**DEBUG MODE ACTIVATED**" or "")

ALLOWED_HOSTS = []
ALLOWED_HOSTS.extend(config.getlist("SECURITY", "ALLOWED_HOSTS", []))

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Application definition

INSTALLED_APPS = [
    "constance",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.forms",
    "django_filters",
    "rest_framework",
    "dbbackup",
    # "corsheaders",
    "import_export",
    "knox",
    "simple_history",
    "django_cron",
    "django_email_verification",
    "notifier",
    "core",
    # 'frontend',
    "anymail",
    "django.contrib.admin",  # after to allow templates override
    "user_visit",
    "loginas",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "user_visit.middleware.UserVisitMiddleware",
    'request_logging.middleware.LoggingMiddleware',
]

ROOT_URLCONF = "location.urls"
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")  # ROOT dir for templates

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATE_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "constance.context_processors.config",
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.media",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.settings",
            ],
        },
    },
]

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

WSGI_APPLICATION = "location.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config.get("DATABASE", "engine", "django.db.backends.sqlite3"),
        "HOST": config.get("DATABASE", "host", ""),
        "PORT": config.getint("DATABASE", "port", 5432),
        "NAME": config.get("DATABASE", "name", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": config.get("DATABASE", "user", "location"),
        "PASSWORD": config.get("DATABASE", "password", ""),
    },
    # 'legacy': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME':   '/Applications/XAMPP/xamppfiles/htdocs/lsai/location3.db',
    # }
}

# DATABASE_ROUTERS = ['core.db_router.Router', ]

AUTH_USER_MODEL = "core.User"

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = ["core.auth_backend.EmailBackend"]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGES = [
    ("fr", _("French")),
    ("en", _("English")),
]

LANGUAGE_CODE = "fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]

STORAGES = {
    "default": {
        "BACKEND": UNITTEST
        and "django.core.files.storage.InMemoryStorage"
        or "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (uploaded, generated PDF, etc...)
MEDIA_ROOT = os.path.join(BASE_DIR, UNITTEST and "files-unittest" or "files")
MEDIA_URL = "/files/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = config.get("APP", "STATIC_URL", "/static/")

# Extra lookup directories for collectstatic to find static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

DJANGO_VITE_ASSETS_PATH = os.path.join(BASE_DIR, "frontend", "build")
DJANGO_VITE_MANIFEST_PATH = os.path.join(DJANGO_VITE_ASSETS_PATH, "vite-manifest.json")
DJANGO_VITE_DEV_MODE = ENV == "dev"  # default to DEBUG

if os.path.exists(DJANGO_VITE_ASSETS_PATH):
    STATICFILES_DIRS.append(DJANGO_VITE_ASSETS_PATH)

# admin user
ADMINS = (("Support", config.get("APP", "EMAIL_ADMIN", "app@tiloc.fr")),)

# Email configuration

EMAIL_BACKEND = config.get("EMAIL", "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")

DEFAULT_FROM_EMAIL = config.get("EMAIL", "DEFAULT_FROM_EMAIL", "Tiloc <app@tiloc.fr>")
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_HOST = config.get("EMAIL", "SMTP_HOST", "smtp-crd.alwaysdata.net")
EMAIL_PORT = 587
EMAIL_HOST_USER = config.get("EMAIL", "SMTP_USER", "")
EMAIL_HOST_PASSWORD = config.get("EMAIL", "SMTP_PASSWORD", "")
EMAIL_USE_TLS = True
EMAIL_SUBJECT_PREFIX = config.get("EMAIL", "SUBJECT_PREFIX", "[Tiloc]") + " "

ANYMAIL = {
    "SENDINBLUE_API_KEY": config.get("EMAIL", "SENDINBLUE_API_KEY", ""),
    "MAILJET_API_KEY": config.get("EMAIL", "MAILJET_API_KEY", ""),
    "MAILJET_SECRET_KEY": config.get("EMAIL", "MAILJET_SECRET_KEY", ""),
}


DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # "knox.auth.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "core.permissions.TilocPermissions",
    ],
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        # "rest_framework.parsers.MultiPartParser",
        "core.parsers.MultiPartJSONParser",
    ],
    "EXCEPTION_HANDLER": "core.views.exception_handler",

}

# if ENV == "dev" and "rest_framework.authentication.SessionAuthentication" not in REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"]:
#     # needed to allow access to /api/ pages
#     REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"].append("rest_framework.authentication.SessionAuthentication")

REST_KNOX = {
    "SECURE_HASH_ALGORITHM": UNITTEST
    and "cryptography.hazmat.primitives.hashes.MD5"
    or "cryptography.hazmat.primitives.hashes.SHA512",  # noqa: E131
    # 'AUTH_TOKEN_CHARACTER_LENGTH': 64,
    "TOKEN_TTL": timedelta(days=30),
    # 'TOKEN_LIMIT_PER_USER': None,
    "AUTO_REFRESH": True,
    "USER_SERIALIZER": "core.serializers.CurrentUserSerializer",
}

APP_NAME = _("Tiloc")

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"
CONSTANCE_CONFIG = {
    "DEBUG": (False, "Turn on DEBUG information on Django"),
    "CAN_SIGNUP": (False, "Turn on/off new accounts signup"),
}

IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_SKIP_ADMIN_LOG = True

CRON_CLASSES = [
    "core.cron.SyncBookingsJob",
    "core.cron.ExportBookingsJob",
    "core.cron.PurgeNotificationsJob",
    # ...
]
DJANGO_CRON_DELETE_LOGS_OLDER_THAN = 30

WKHTMLTOPDF_PATH = config.get("PDF", "WKHTMLTOPDF_PATH", "wkhtmltopdf")


def get_backup_filename(**kwargs):
    return "tiloc-{servername}-{datetime}-v{version}.{extension}".format(**dict(kwargs, **{"version": __version__}))


DBBACKUP_STORAGE = "django.core.files.storage.FileSystemStorage"
DBBACKUP_STORAGE_OPTIONS = {"location": os.path.join(BASE_DIR, "backups")}
DBBACKUP_FILENAME_TEMPLATE = get_backup_filename
# DBBACKUP_CONNECTORS = {"default": {"SINGLE_TRANSACTION": False}}

DEMO_ACCOUNT_NAME = "__demo__"


def email_verified_callback(user):
    user.verified = True
    user.save(update_fields=("verified",))


def password_change_callback(user, password):
    user.set_password(password)
    user.save(update_fields=("password",))


# Global Package Settings
EMAIL_FROM_ADDRESS = "Cédric de Tiloc <noreply@tiloc.fr>"  # mandatory
EMAIL_PAGE_DOMAIN = config.get(
    "EMAIL_VERIFICATION", "PAGE_DOMAIN", "https://app.tiloc.fr/"
)  # mandatory (unless you use a custom link)
EMAIL_MULTI_USER = False  # optional (defaults to False)

# Email Verification Settings (mandatory for email sending)
EMAIL_MAIL_SUBJECT = "Veuillez confirmer votre compte {{ user.first_name }}"
EMAIL_MAIL_HTML = "signup/mail_body.html"
EMAIL_MAIL_PLAIN = "signup/mail_body.txt"
EMAIL_MAIL_TOKEN_LIFE = 60 * 60  # one hour

# Email Verification Settings (mandatory for builtin view)
EMAIL_MAIL_PAGE_TEMPLATE = "signup/email_success_template.html"
EMAIL_MAIL_CALLBACK = email_verified_callback

# Password Recovery Settings (mandatory for email sending)
EMAIL_PASSWORD_SUBJECT = "Vos informations de connexion {{ user.firstname }}"
EMAIL_PASSWORD_HTML = "password/password_body.html"
EMAIL_PASSWORD_PLAIN = "password/password_body.txt"
EMAIL_PASSWORD_TOKEN_LIFE = 60 * 10  # 10 minutes

# Password Recovery Settings (mandatory for builtin view)
EMAIL_PASSWORD_PAGE_TEMPLATE = "password/password_changed_template.html"
EMAIL_PASSWORD_CHANGE_PAGE_TEMPLATE = "password/password_change_template.html"
EMAIL_PASSWORD_CALLBACK = password_change_callback

# For Django Email Backend
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

STRIPE_PUBLIC_API_KEY = config.get("STRIPE", "PUBLIC_API_KEY", "")
STRIPE_PRIVATE_API_KEY = config.get("STRIPE", "PRIVATE_API_KEY", "")
STRIPE_ENDPOINT_SECRET = config.get("STRIPE", "ENDPOINT_SECRET", "")
STRIPE_CUSTOMER_DASHBOARD_URL = config.get("STRIPE", "CUSTOMER_DASHBOARD_URL", "")
STRIPE_TEST_MODE = STRIPE_PRIVATE_API_KEY.startswith("sk_test_")


NOTIFIER_BACKENDS = (
    "notifier.backends.EmailBackend",
    "core.notifier_backend.NoopBackend",
)
NOTIFIER_THREADED_EMAIL = not UNITTEST

LOGINAS_REDIRECT_URL = '/'
LOGOUT_URL = reverse_lazy('loginas-logout')
LOGINAS_LOGOUT_REDIRECT_URL = reverse_lazy('admin:index')
LOGINAS_USERNAME_FIELD = 'email'

REQUEST_LOGGING_ENABLE_COLORIZE = False
